/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/accessories/': RouteRecordInfo<
      '/accessories/',
      '/accessories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/architecture/': RouteRecordInfo<
      '/architecture/',
      '/architecture',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/stone/': RouteRecordInfo<
      '/stone/',
      '/stone',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tombstone/': RouteRecordInfo<
      '/tombstone/',
      '/tombstone',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/work/': RouteRecordInfo<
      '/work/',
      '/work',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/accessories/index.vue': {
      routes:
        | '/accessories/'
      views:
        | never
    }
    'src/pages/architecture/index.vue': {
      routes:
        | '/architecture/'
      views:
        | never
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
    }
    'src/pages/stone/index.vue': {
      routes:
        | '/stone/'
      views:
        | never
    }
    'src/pages/tombstone/index.vue': {
      routes:
        | '/tombstone/'
      views:
        | never
    }
    'src/pages/work/index.vue': {
      routes:
        | '/work/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
