<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AccessorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('accessories')->insert([
            // Kő váza
            [
                'order' => 1,
                'accessory_id' => 'NR 1',
                'name' => 'Szögletes, fózolt váza',
                'type' => 'Szögletes, fózolt kőváza',
                'size' => '20x10x10cm, 25x10x10cm, 30x10x10cm, 30x15x15cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Sima fényezett, nyers vagy polírozott ferde fózolással',
                'image_url' => '/storage/accessories/NR1.jpg',
                'group' => 'NR1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'accessory_id' => 'NR 2',
                'name' => 'Szögletes, ívfózolt váza',
                'type' => 'Szögletes, ívfózolt kőváza',
                'size' => '20x10x10cm, 25x10x10cm, 30x10x10cm, 30x15x15cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Sima fényezett, nyers vagy polírozott íves fózolással',
                'image_url' => '/storage/accessories/NR2.jpg',
                'group' => 'NR1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'accessory_id' => 'NR 3',
                'name' => 'Szögletes, trapézfózolt váza',
                'type' => 'Szögletes, álló trapézfózolt kőváza',
                'size' => '20x10x10cm, 25x10x10cm, 30x10x10cm, 30x15x15cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Sima fényezett, nyers vagy polírozott álló trapéz fózolással',
                'image_url' => '/storage/accessories/NR3.jpg',
                'group' => 'NR1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'accessory_id' => 'NR 4',
                'name' => 'Szögletes, trapéz váza',
                'type' => 'Szögletes, trapéz kőváza',
                'size' => '20x10x10cm, 25x10x10cm, 30x15x15cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Sima fényezett',
                'image_url' => '/storage/accessories/NR4.jpg',
                'group' => 'NR1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'accessory_id' => 'NR 5',
                'name' => 'Szögletes, álló hasáb váza',
                'type' => 'Szögletes, álló hasáb kőváza',
                'size' => '20x10x10cm, 25x10x10cm, 30x10x10cm, 30x15x15cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Sima fényezett',
                'image_url' => '/storage/accessories/NR5.jpg',
                'group' => 'NR1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'accessory_id' => 'NR 6',
                'name' => 'Szögletes, trapéz váza',
                'type' => 'Szögletes, trapéz kőváza',
                'size' => '20x10x10cm, 25x10x10cm, 30x15x15cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Sima fényezett és hasított, faragott',
                'image_url' => '/storage/accessories/NR6.jpg',
                'group' => 'NR1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'accessory_id' => 'NR 7',
                'name' => 'Hasított, faragott váza',
                'type' => 'Hasított, faragott kőváza',
                'size' => '20x15x15cm, 25x15x15cm, 30x15x15cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Hasított, faragott',
                'image_url' => '/storage/accessories/NR7.jpg',
                'group' => 'NR1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'accessory_id' => 'NR 8',
                'name' => 'Esztergált váza',
                'type' => 'Görög" esztergált kőváza',
                'size' => '25x12x12cm, 30x12x12cm 30x15x15cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Esztergált',
                'image_url' => '/storage/accessories/NR8.jpg',
                'group' => 'NR1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'accessory_id' => 'NR 9',
                'name' => 'Esztergált váza',
                'type' => 'Esztergált kőváza',
                'size' => '25x14x14cm, 30x14x14cm 32x16x16cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Esztergált',
                'image_url' => '/storage/accessories/NR9.jpg',
                'group' => 'NR1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'accessory_id' => 'NR 10',
                'name' => 'Esztergált váza',
                'type' => 'Esztergált kőváza',
                'size' => '30x14x14cm 32x16x16cm, 32x18x18cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Esztergált',
                'image_url' => '/storage/accessories/NR10.jpg',
                'group' => 'NR1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 11,
                'accessory_id' => 'NR 11',
                'name' => 'Esztergált váza',
                'type' => 'Esztergált kőváza',
                'size' => '25x14x14cm, 30x14x14cm 32x16x16cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Esztergált',
                'image_url' => '/storage/accessories/NR11.jpg',
                'group' => 'NR1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 12,
                'accessory_id' => 'NR 12',
                'name' => 'Esztergált váza',
                'type' => 'Esztergált kőváza',
                'size' => '25x14x14cm, 30x14x14cm 32x16x16cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Esztergált',
                'image_url' => '/storage/accessories/NR12.jpg',
                'group' => 'NR1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 13,
                'accessory_id' => 'NR 13',
                'name' => 'Esztergált váza',
                'type' => 'Esztergált kőváza',
                'size' => '25x14x14cm, 30x14x14cm 32x16x16cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Esztergált',
                'image_url' => '/storage/accessories/NR13.jpg',
                'group' => 'NR1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 14,
                'accessory_id' => 'NR 14',
                'name' => 'Esztergált váza',
                'type' => 'Esztergált kőváza',
                'size' => '25x20x20cm, 25x25x25cm, 30x30x30cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Esztergált',
                'image_url' => '/storage/accessories/NR14.jpg',
                'group' => 'NR1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Kő mécsestartó
            [
                'order' => 1,
                'accessory_id' => 'L 1',
                'name' => 'Esztergált, kér oldali mécsestartó',
                'type' => 'Esztergált, két oldali mécsestartó',
                'size' => '15x25cm',
                'recommended_type' => 'Gránit',
                'manufacturing_technology' => 'Esztergált, felül nyitható',
                'image_url' => '/storage/accessories/L1.jpg',
                'group' => 'L1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'accessory_id' => 'L 2',
                'name' => 'Esztergált, egy oldali mécsestartó',
                'type' => 'Esztergált, egy oldali mécsestartó',
                'size' => '15x25cm',
                'recommended_type' => 'Gránit',
                'manufacturing_technology' => 'Esztergált, felül nyitható',
                'image_url' => '/storage/accessories/L2.jpg',
                'group' => 'L1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'accessory_id' => 'L 3',
                'name' => 'Szögletes, négy ablakos mécsestartó',
                'type' => 'Szögletes, négyablakos mécsestartó',
                'size' => '14x14x25cm',
                'recommended_type' => 'Gránit',
                'manufacturing_technology' => 'Sima fényezett, oldalt nyitható',
                'image_url' => '/storage/accessories/L3.jpg',
                'group' => 'L1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'accessory_id' => 'L 4',
                'name' => 'Kerekített, négy ablakos mécsestartó',
                'type' => 'Kerekített, négyablakos mécsestartó',
                'size' => '14x14x25cm',
                'recommended_type' => 'Gránit',
                'manufacturing_technology' => 'Sima fényezett, oldalt nyitható',
                'image_url' => '/storage/accessories/L4.jpg',
                'group' => 'L1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'accessory_id' => 'L 5',
                'name' => 'Esztergált, négy ablakos mécsestartó',
                'type' => 'Esztergált, négyablakos mécsestartó',
                'size' => '16x25cm',
                'recommended_type' => 'Gránit',
                'manufacturing_technology' => 'Esztergált, oldalt nyitható',
                'image_url' => '/storage/accessories/L5.jpg',
                'group' => 'L1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'accessory_id' => 'L 6',
                'name' => 'Natúr mécsestartó',
                'type' => 'Natúr mécsestartó',
                'size' => '10x10x3cm, 10x10x5cm, 10x10x8cm, 10x10x10cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Sima fényezett, fúrt',
                'image_url' => '/storage/accessories/L6.jpg',
                'group' => 'L1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Kő virágtartó
            [
                'order' => 1,
                'accessory_id' => 'NR 1',
                'name' => 'Esztergált, kő kaspó',
                'type' => 'Esztergált tálváza',
                'size' => '30x16cm',
                'recommended_type' => 'Gránit',
                'manufacturing_technology' => 'Esztergált',
                'image_url' => '/storage/accessories/NR2-1.jpg',
                'group' => 'NR2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'accessory_id' => 'NR 2',
                'name' => 'Esztergált, kő kaspó',
                'type' => 'Esztergált tálváza',
                'size' => '30x16cm',
                'recommended_type' => 'Gránit',
                'manufacturing_technology' => 'Esztergált',
                'image_url' => '/storage/accessories/NR2-2.jpg',
                'group' => 'NR2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'accessory_id' => 'NR 3',
                'name' => 'Esztergált, kő kaspó',
                'type' => 'Esztergált tálváza',
                'size' => '30x16cm',
                'recommended_type' => 'Gránit',
                'manufacturing_technology' => 'Esztergált',
                'image_url' => '/storage/accessories/NR2-3.jpg',
                'group' => 'NR2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'accessory_id' => 'NR 4',
                'name' => 'Esztergált, kő kaspó',
                'type' => 'Esztergált tálváza',
                'size' => '30x16cm',
                'recommended_type' => 'Gránit',
                'manufacturing_technology' => 'Esztergált',
                'image_url' => '/storage/accessories/NR2-4.jpg',
                'group' => 'NR2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'accessory_id' => 'NR 5',
                'name' => 'Esztergált, kő kaspó',
                'type' => 'Esztergált tálváza',
                'size' => '30x16cm',
                'recommended_type' => 'Gránit',
                'manufacturing_technology' => 'Esztergált',
                'image_url' => '/storage/accessories/NR2-5.jpg',
                'group' => 'NR2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'accessory_id' => 'NR 6',
                'name' => 'Esztergált, kő kaspó',
                'type' => 'Esztergált tálváza',
                'size' => '30x16cm',
                'recommended_type' => 'Gránit',
                'manufacturing_technology' => 'Esztergált',
                'image_url' => '/storage/accessories/NR2-6.jpg',
                'group' => 'NR2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'accessory_id' => 'NR 7',
                'name' => 'Esztergált, kő kaspó',
                'type' => 'Esztergált tálváza',
                'size' => '30x16cm',
                'recommended_type' => 'Gránit',
                'manufacturing_technology' => 'Esztergált',
                'image_url' => '/storage/accessories/NR2-7.jpg',
                'group' => 'NR2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'accessory_id' => 'NR 8',
                'name' => 'Faragott, tömb virágláda',
                'type' => 'Tömb gránit virágláda',
                'size' => '50x30x20cm, 80x30x20cm, 100x35x25cm',
                'recommended_type' => 'Gránit',
                'manufacturing_technology' => 'Faragott, hasított',
                'image_url' => '/storage/accessories/NR2-8.jpg',
                'group' => 'NR2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Sírfelirat
            [
                'order' => 1,
                'accessory_id' => '',
                'name' => 'Times New Roman',
                'type' => 'Talpas, vastagíhtató',
                'size' => '20mm',
                'recommended_type' => 'Sötét gránit és márvány',
                'manufacturing_technology' => 'homokfújt',
                'image_url' => '/storage/accessories/sirfelirat1.jpg',
                'group' => 'sirfelirat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'accessory_id' => '',
                'name' => 'Bookman Old Style',
                'type' => 'Talpas, vastagíhtató',
                'size' => '20mm',
                'recommended_type' => 'Összes gránit, márvány, mészkő',
                'manufacturing_technology' => 'homokfújt',
                'image_url' => '/storage/accessories/sirfelirat2.jpg',
                'group' => 'sirfelirat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'accessory_id' => '',
                'name' => 'Lydian Cursive BT',
                'type' => 'Írott, díszítő',
                'size' => '35mm kezdő karakter',
                'recommended_type' => 'Összes gránit, márvány, mészkő',
                'manufacturing_technology' => 'homokfújt',
                'image_url' => '/storage/accessories/sirfelirat3.jpg',
                'group' => 'sirfelirat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'accessory_id' => '',
                'name' => 'Commercial Script BT',
                'type' => 'Írott, díszítő',
                'size' => '40mm kezdő karakter',
                'recommended_type' => 'Sötét gránit és márvány',
                'manufacturing_technology' => 'homokfújt',
                'image_url' => '/storage/accessories/sirfelirat4.jpg',
                'group' => 'sirfelirat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'accessory_id' => '',
                'name' => 'Bell MT',
                'type' => 'Talpas, vastagíhtató',
                'size' => '20mm',
                'recommended_type' => 'Összes kőtípusra',
                'manufacturing_technology' => 'homokfújt',
                'image_url' => '/storage/accessories/sirfelirat5.jpg',
                'group' => 'sirfelirat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'accessory_id' => '',
                'name' => 'Székely-magyar rovásírás',
                'type' => 'Talpas, díszítő',
                'size' => '30mm',
                'recommended_type' => 'Összes gránit, márvány',
                'manufacturing_technology' => 'homokfújt',
                'image_url' => '/storage/accessories/sirfelirat6.jpg',
                'group' => 'sirfelirat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'accessory_id' => '',
                'name' => 'Talpatlan, díszítő',
                'type' => 'Héber rás',
                'size' => '30mm',
                'recommended_type' => 'Összes gránit, márvány, mészkő',
                'manufacturing_technology' => 'homokfújt',
                'image_url' => '/storage/accessories/sirfelirat7.jpg',
                'group' => 'sirfelirat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'accessory_id' => '',
                'name' => 'Ciril írás',
                'type' => 'Talpas, díszítő',
                'size' => '30mm',
                'recommended_type' => 'Összes kőtípusra',
                'manufacturing_technology' => 'homokfújt',
                'image_url' => '/storage/accessories/sirfelirat8.jpg',
                'group' => 'sirfelirat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'accessory_id' => '',
                'name' => 'Corsivo',
                'type' => 'Broz, arany, sötét bronz',
                'size' => '55 mm kezdő karakter',
                'recommended_type' => 'Összes kőtípusra',
                'manufacturing_technology' => 'Fúrt és ragasztott bronz',
                'image_url' => '/storage/accessories/sirfelirat9.jpg',
                'group' => 'sirfelirat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'accessory_id' => '',
                'name' => 'Romano, Mundial',
                'type' => 'Broz, arany, sötét bronz',
                'size' => '55 mm kezdő karakter',
                'recommended_type' => 'Összes kőtípusra',
                'manufacturing_technology' => 'Fúrt és ragasztott bronz',
                'image_url' => '/storage/accessories/sirfelirat10.jpg',
                'group' => 'sirfelirat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
