<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AccessorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('accessories')->insert([
            // Kő váza
            [
                'order' => 1,
                'accessory_id' => 'Nr 1',
                'name' => 'Szögletes, fózolt váza',
                'type' => 'Szögletes, fózolt kőváza',
                'size' => '20x10x10cm, 25x10x10cm, 30x10x10cm, 30x15x15cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Sima fényezett, nyers vagy polírozott ferde fózolással',
                'image_url' => '/storage/accessories/Nr1.jpg',
                'group' => 'Nr1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'accessory_id' => 'Nr 2',
                'name' => 'Szögletes, ívfózolt váza',
                'type' => 'Szögletes, ívfózolt kőváza',
                'size' => '20x10x10cm, 25x10x10cm, 30x10x10cm, 30x15x15cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Sima fényezett, nyers vagy polírozott íves fózolással',
                'image_url' => '/storage/accessories/Nr2.jpg',
                'group' => 'Nr1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'accessory_id' => 'Nr 3',
                'name' => 'Szögletes, trapézfózolt váza',
                'type' => 'Szögletes, álló trapézfózolt kőváza',
                'size' => '20x10x10cm, 25x10x10cm, 30x10x10cm, 30x15x15cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Sima fényezett, nyers vagy polírozott álló trapéz fózolással',
                'image_url' => '/storage/accessories/Nr3.jpg',
                'group' => 'Nr1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'accessory_id' => 'Nr 4',
                'name' => 'Szögletes, trapéz váza',
                'type' => 'Szögletes, trapéz kőváza',
                'size' => '20x10x10cm, 25x10x10cm, 30x15x15cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Sima fényezett',
                'image_url' => '/storage/accessories/Nr4.jpg',
                'group' => 'Nr1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'accessory_id' => 'Nr 5',
                'name' => 'Szögletes, álló hasáb váza',
                'type' => 'Szögletes, álló hasáb kőváza',
                'size' => '20x10x10cm, 25x10x10cm, 30x10x10cm, 30x15x15cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Sima fényezett',
                'image_url' => '/storage/accessories/Nr5.jpg',
                'group' => 'Nr1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'accessory_id' => 'Nr 6',
                'name' => 'Szögletes, trapéz váza',
                'type' => 'Szögletes, trapéz kőváza',
                'size' => '20x10x10cm, 25x10x10cm, 30x15x15cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Sima fényezett és hasított, faragott',
                'image_url' => '/storage/accessories/Nr6.jpg',
                'group' => 'Nr1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'accessory_id' => 'Nr 7',
                'name' => 'Hasított, faragott váza',
                'type' => 'Hasított, faragott kőváza',
                'size' => '20x15x15cm, 25x15x15cm, 30x15x15cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Hasított, faragott',
                'image_url' => '/storage/accessories/Nr7.jpg',
                'group' => 'Nr1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'accessory_id' => 'Nr 8',
                'name' => 'Esztergált váza',
                'type' => 'Görög" esztergált kőváza',
                'size' => '25x12x12cm, 30x12x12cm 30x15x15cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Esztergált',
                'image_url' => '/storage/accessories/Nr8.jpg',
                'group' => 'Nr1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'accessory_id' => 'Nr 9',
                'name' => 'Esztergált váza',
                'type' => 'Esztergált kőváza',
                'size' => '25x14x14cm, 30x14x14cm 32x16x16cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Esztergált',
                'image_url' => '/storage/accessories/Nr9.jpg',
                'group' => 'Nr1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'accessory_id' => 'Nr 10',
                'name' => 'Esztergált váza',
                'type' => 'Esztergált kőváza',
                'size' => '30x14x14cm 32x16x16cm, 32x18x18cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Esztergált',
                'image_url' => '/storage/accessories/Nr10.jpg',
                'group' => 'Nr1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 11,
                'accessory_id' => 'Nr 11',
                'name' => 'Esztergált váza',
                'type' => 'Esztergált kőváza',
                'size' => '25x14x14cm, 30x14x14cm 32x16x16cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Esztergált',
                'image_url' => '/storage/accessories/Nr11.jpg',
                'group' => 'Nr1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 12,
                'accessory_id' => 'Nr 12',
                'name' => 'Esztergált váza',
                'type' => 'Esztergált kőváza',
                'size' => '25x14x14cm, 30x14x14cm 32x16x16cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Esztergált',
                'image_url' => '/storage/accessories/Nr12.jpg',
                'group' => 'Nr1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 13,
                'accessory_id' => 'Nr 13',
                'name' => 'Esztergált váza',
                'type' => 'Esztergált kőváza',
                'size' => '25x14x14cm, 30x14x14cm 32x16x16cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Esztergált',
                'image_url' => '/storage/accessories/Nr13.jpg',
                'group' => 'Nr1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 14,
                'accessory_id' => 'Nr 14',
                'name' => 'Esztergált váza',
                'type' => 'Esztergált kőváza',
                'size' => '25x20x20cm, 25x25x25cm, 30x30x30cm',
                'recommended_type' => 'Gránit, márvány, mészkő',
                'manufacturing_technology' => 'Esztergált',
                'image_url' => '/storage/accessories/Nr14.jpg',
                'group' => 'Nr1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Kő váza
        ]);
    }
}
