<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArchitectureSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('architectures')->insert([
            // Konyhapult
            [
                'order' => 1,
                'name' => 'Paradiso Classico gránit',
                'image_url' => '/storage/architectures/konyhapult1.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'Rosso Vanga gránit',
                'image_url' => '/storage/architectures/konyhapult2.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'Rosa Beta gránit',
                'image_url' => '/storage/architectures/konyhapult3.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'Nero Assoluto Indian',
                'image_url' => '/storage/architectures/konyhapult4.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'name' => 'Tiger Skin gránit',
                'image_url' => '/storage/architectures/konyhapult5.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'name' => 'Tiger Skin gránit',
                'image_url' => '/storage/architectures/konyhapult6.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'name' => 'Nero Africa Impala gránit',
                'image_url' => '/storage/architectures/konyhapult7.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'name' => 'Nero Africa Impala gránit',
                'image_url' => '/storage/architectures/konyhapult8.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'name' => 'Verde San Francisco gránit',
                'image_url' => '/storage/architectures/konyhapult9.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'name' => 'Verde San Francisco gránit',
                'image_url' => '/storage/architectures/konyhapult10.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 11,
                'name' => 'Halmstadt gránit',
                'image_url' => '/storage/architectures/konyhapult11.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 12,
                'name' => 'Giallo Veneziano gránit',
                'image_url' => '/storage/architectures/konyhapult12.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 13,
                'name' => 'Giallo Veneziano gránit',
                'image_url' => '/storage/architectures/konyhapult13.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 14,
                'name' => 'Verde Laguna gránit',
                'image_url' => '/storage/architectures/konyhapult14.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 15,
                'name' => 'Verde Laguna gránit',
                'image_url' => '/storage/architectures/konyhapult15.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 16,
                'name' => 'Verde Laguna gránit',
                'image_url' => '/storage/architectures/konyhapult16.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 17,
                'name' => 'Verde Laguna gránit',
                'image_url' => '/storage/architectures/konyhapult17.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 18,
                'name' => 'Verde Laguna gránit',
                'image_url' => '/storage/architectures/konyhapult18.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 19,
                'name' => 'Nero Assoluto Indian gránit',
                'image_url' => '/storage/architectures/konyhapult19.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'order' => 20,
                'name' => 'Nero Assoluto Indian gránit',
                'image_url' => '/storage/architectures/konyhapult20.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 21,
                'name' => 'Nero Assoluto Indian gránit',
                'image_url' => '/storage/architectures/konyhapult21.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 22,
                'name' => 'Nero Assoluto Indian gránit',
                'image_url' => '/storage/architectures/konyhapult22.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 23,
                'name' => 'Giallo Veneziano gránit pult',
                'image_url' => '/storage/architectures/konyhapult23.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Fürdőszobapult
            [
                'order' => 1,
                'name' => 'Copacabana gránit fürdőszobapult, Hilton Budapest',
                'image_url' => '/storage/architectures/furdoszobapult1.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'Copacabana gránitfürdőszobapult, Hilton Budapest, 3. emelet',
                'image_url' => '/storage/architectures/furdoszobapult2.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'Copacabana gránitfürdőszobapult, Hilton Budapest, 3. emelet',
                'image_url' => '/storage/architectures/furdoszobapult3.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'Copacabana gránit fürdőszobapult, Hilton Budapest',
                'image_url' => '/storage/architectures/furdoszobapult4.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'name' => 'Copacabana gránit fürdőszobapult, Hilton Budapest',
                'image_url' => '/storage/architectures/furdoszobapult5.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'name' => 'Copacabana gránit fürdőszobapult, Hilton Budapest',
                'image_url' => '/storage/architectures/furdoszobapult6.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'name' => 'Schöderhamn gránit közösségi mosdók, Hilton Budapest',
                'image_url' => '/storage/architectures/furdoszobapult7.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'name' => 'Brazulite gránit közösségi mosdók, Hilton Budapest',
                'image_url' => '/storage/architectures/furdoszobapult8.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'name' => 'Schöderhamn gránit közösségi mosdók, Hilton Budapest',
                'image_url' => '/storage/architectures/furdoszobapult9.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'name' => 'Azul Bahia gránit fürdőszobapult, Hilton Budapest, elnöki lakosztály',
                'image_url' => '/storage/architectures/furdoszobapult10.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 11,
                'name' => 'Via Lattea gránit mosdópult',
                'image_url' => '/storage/architectures/furdoszobapult11.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 12,
                'name' => 'Labrador Blue LGHQ gránit fürdőszobapul',
                'image_url' => '/storage/architectures/furdoszobapult12.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 13,
                'name' => 'Nero Assoluto India gránit fürdőkád körüli burkolat',
                'image_url' => '/storage/architectures/furdoszobapult13.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 14,
                'name' => 'Jura Beige mészkő fürdőkád körüli burkolat',
                'image_url' => '/storage/architectures/furdoszobapult14.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 15,
                'name' => 'Azul Bahia gránit fürdőkád körülidíszburkolat, Hilton Budapest, elnöki lakosztály',
                'image_url' => '/storage/architectures/furdoszobapult15.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 16,
                'name' => 'Giallo Veneziano gránit fürdőszobapult',
                'image_url' => '/storage/architectures/furdoszobapult16.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 17,
                'name' => 'Via Lattea gránit fürdőkád körüli burkolat és díszhomlokzat',
                'image_url' => '/storage/architectures/furdoszobapult17.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 18,
                'name' => 'zul Bahia gránit fürdőkád körüli díszburkolat, Hilton Budapest, elnöki lakosztály',
                'image_url' => '/storage/architectures/furdoszobapult18.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Lépcsőburkolat
            [
                'order' => 1,
                'name' => 'Nilo River gránit íves lépcsőburkolat',
                'image_url' => '/storage/architectures/lepcsoburkolat1.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'Silver Star gránit lépcsőburkolat',
                'image_url' => '/storage/architectures/lepcsoburkolat2.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'Silver Star gránit lépcsőburkolat',
                'image_url' => '/storage/architectures/lepcsoburkolat3.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'Silver Star gránit lépcsőburkolat',
                'image_url' => '/storage/architectures/lepcsoburkolat4.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'name' => 'Nero Assoluto India gránit lépcsőburkolat',
                'image_url' => '/storage/architectures/lepcsoburkolat5.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'name' => 'Nero Assoluto India gránit lépcsőburkolat',
                'image_url' => '/storage/architectures/lepcsoburkolat6.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'name' => 'Nero Assoluto India gránit lépcsőburkolat',
                'image_url' => '/storage/architectures/lepcsoburkolat7.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'name' => 'Nero Assoluto India gránit lépcsőburkolat',
                'image_url' => '/storage/architectures/lepcsoburkolat8.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'name' => 'Rosso Verona márvány lépcsőburkolat',
                'image_url' => '/storage/architectures/lepcsoburkolat9.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'name' => 'Monaco gránit lépcsőburkolat',
                'image_url' => '/storage/architectures/lepcsoburkolat10.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 11,
                'name' => 'Silver Star gránit lépcsőburkolat',
                'image_url' => '/storage/architectures/lepcsoburkolat11.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 12,
                'name' => 'Verde Marina gránit kőlépcső',
                'image_url' => '/storage/architectures/lepcsoburkolat12.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 13,
                'name' => 'Nero Assoluto India gránit lépcsőburkolat',
                'image_url' => '/storage/architectures/lepcsoburkolat13.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 14,
                'name' => 'Silver Star gránit lépcsőburkolat',
                'image_url' => '/storage/architectures/lepcsoburkolat14.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 15,
                'name' => 'Jura Gelb mészkő lépcsőburkolat',
                'image_url' => '/storage/architectures/lepcsoburkolat15.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 16,
                'name' => 'Bianco Tarn gránit ívesre fazonozott durva felületű tömb kőlépcső',
                'image_url' => '/storage/architectures/lepcsoburkolat16.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 17,
                'name' => 'Blue Stone tömb kőlépcső szakított faragott oldallal homokszórt antikolt felülettel',
                'image_url' => '/storage/architectures/lepcsoburkolat17.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 18,
                'name' => 'Buff Grey kvarcit tömb kőlépcső és burkolat',
                'image_url' => '/storage/architectures/lepcsoburkolat18.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 19,
                'name' => 'Jura Gelb mészkő tömb kőlépcső mattcsiszolt felülettel',
                'image_url' => '/storage/architectures/lepcsoburkolat19.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 20,
                'name' => 'Royal Mahogany gránit lépcsőburkolat égetett flammolt felülettel',
                'image_url' => '/storage/architectures/lepcsoburkolat20.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 21,
                'name' => 'Royal Mahogany gránit lépcsőburkolat égetett flammolt felülettel',
                'image_url' => '/storage/architectures/lepcsoburkolat21.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 22,
                'name' => 'Royal Mahogany gránit lépcsőburkolat égetett flammolt felülettel',
                'image_url' => '/storage/architectures/lepcsoburkolat22.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 23,
                'name' => 'Rosa Beta belépő és Nero Impala homlok gránit lépcsőburkolat',
                'image_url' => '/storage/architectures/lepcsoburkolat23.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 24,
                'name' => 'Impala Light gránit lépcsőburkolat antikolt gyémántkefélt felülettel',
                'image_url' => '/storage/architectures/lepcsoburkolat24.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 25,
                'name' => 'Nero Impala gránit lépcsőburkolat mattcsiszolt felülettel',
                'image_url' => '/storage/architectures/lepcsoburkolat25.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 26,
                'name' => 'Jura Gelb mészkő lépcsőburkolat',
                'image_url' => '/storage/architectures/lepcsoburkolat26.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 27,
                'name' => 'Jura Gelb mészkő lépcsőburkolat',
                'image_url' => '/storage/architectures/lepcsoburkolat27.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 28,
                'name' => 'Rosa Beta gránit könnyűszerkezetes tömb kőlépcső mattcsiszolt felülettel',
                'image_url' => '/storage/architectures/lepcsoburkolat28.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 29,
                'name' => 'Rosa Porrino gránit könnyűszerkezetes tömb kőlépcső antikolt gyémántkefélt felülettel',
                'image_url' => '/storage/architectures/lepcsoburkolat29.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 30,
                'name' => 'Silver Star gránit könnyűszerkezetes tömb kőlépcső mattcsiszolt felülettel',
                'image_url' => '/storage/architectures/lepcsoburkolat30.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 31,
                'name' => 'Rosa Beta tömb kőlépcső égetett flammolt felülettel szakított sprengelt oldallal ívesen kialakítva',
                'image_url' => '/storage/architectures/lepcsoburkolat31.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 32,
                'name' => 'Silver Star gránit tömb kőlépcső és burkolat mattcsiszolt felülettel',
                'image_url' => '/storage/architectures/lepcsoburkolat32.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 33,
                'name' => 'Supergrey gránit tömb kőlépcső nyers durva felülettel',
                'image_url' => '/storage/architectures/lepcsoburkolat33.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Kerítés fedkő
            [
                'order' => 1,
                'name' => 'Jura Gelb mészkő kerítésfedkő, kerítésfedlap faragott szakított éllel és mattcsiszolt felülettel',
                'image_url' => '/storage/architectures/keritesfedko1.jpg',
                'group' => 'keritesfedko',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'Nero Impala gránit kerítésfedkő kerítésfedlap fényezett felülettel',
                'image_url' => '/storage/architectures/keritesfedko2.jpg',
                'group' => 'keritesfedko',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'Rio Preto gránit ívelt formájú fedkő fedlap mattcsiszolt felülettel',
                'image_url' => '/storage/architectures/keritesfedko3.jpg',
                'group' => 'keritesfedko',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'Rio Preto gránit kerítésfedkő kerítésfedlap kúpos prizmás kialakítással mattcsiszolt felülettel',
                'image_url' => '/storage/architectures/keritesfedko4.jpg',
                'group' => 'keritesfedko',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'name' => 'Rio Preto gránit kerítésfedkő kerítésfedlap mattcsiszolt felülettel',
                'image_url' => '/storage/architectures/keritesfedko5.jpg',
                'group' => 'keritesfedko',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'name' => 'Rosa Porrino gránit kerítésfedkő kerítésfedlap fényezett felülettel',
                'image_url' => '/storage/architectures/keritesfedko6.jpg',
                'group' => 'keritesfedko',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'name' => 'Silver Star gránit kerítésfedkő kerítésfedlap kúpos prizmás kialakítással fényezett felülettel',
                'image_url' => '/storage/architectures/keritesfedko7.jpg',
                'group' => 'keritesfedko',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'name' => 'Steel Grey gránit kerítésfedkő kerítésfedlap gyémántkefélt antikolt felülettel',
                'image_url' => '/storage/architectures/keritesfedko8.jpg',
                'group' => 'keritesfedko',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Kőkorlát
            [
                'order' => 1,
                'name' => 'Baluszter kőkorlát mészkőből és márványból',
                'image_url' => '/storage/architectures/kokorlat1.jpg',
                'group' => 'kokorlat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'Baluszter kőkorlát mészkőből és márványból',
                'image_url' => '/storage/architectures/kokorlat2.jpg',
                'group' => 'kokorlat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'Baluszter kőkorlát mészkőből és márványból',
                'image_url' => '/storage/architectures/kokorlat3.jpg',
                'group' => 'kokorlat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'Baluszter kőkorlát mészkőből és márványból',
                'image_url' => '/storage/architectures/kokorlat4.jpg',
                'group' => 'kokorlat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'name' => 'Baluszter kőkorlát mészkőből és márványból',
                'image_url' => '/storage/architectures/kokorlat5.jpg',
                'group' => 'kokorlat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'name' => 'Baluszter kőkorlát mészkőből és márványból',
                'image_url' => '/storage/architectures/kokorlat6.jpg',
                'group' => 'kokorlat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'name' => 'Baluszter kőkorlát mészkőből és márványból',
                'image_url' => '/storage/architectures/kokorlat7.jpg',
                'group' => 'kokorlat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'name' => 'Baluszter kőkorlát mészkőből és márványból',
                'image_url' => '/storage/architectures/kokorlat8.jpg',
                'group' => 'kokorlat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Kőkorlát típusok
            [
                'order' => 1,
                'name' => 'Baluszter kőkorlát mészkőből és márványból Sevilla típus',
                'image_url' => '/storage/architectures/kokorlattipusok1.jpg',
                'group' => 'kokorlattipusok',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'Baluszter kőkorlát mészkőből és márványból Sevilla típus',
                'image_url' => '/storage/architectures/kokorlattipusok2.jpg',
                'group' => 'kokorlattipusok',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'Baluszter kőkorlát mészkőből és márványból Sevilla típus',
                'image_url' => '/storage/architectures/kokorlattipusok3.jpg',
                'group' => 'kokorlattipusok',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'Baluszter kőkorlát mészkőből és márványból Sevilla típus',
                'image_url' => '/storage/architectures/kokorlattipusok4.jpg',
                'group' => 'kokorlattipusok',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Kandalló
            [
                'order' => 1,
                'name' => 'Klasszikus stílusú kandalló márványból',
                'image_url' => '/storage/architectures/kandallo1.jpg',
                'group' => 'kandallo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'Klasszikus stílusú kandalló márványból',
                'image_url' => '/storage/architectures/kandallo2.jpg',
                'group' => 'kandallo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'Klasszikus stílusú kandalló márványból',
                'image_url' => '/storage/architectures/kandallo3.jpg',
                'group' => 'kandallo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'Minimál stílusú modern kandalló mészkőből',
                'image_url' => '/storage/architectures/kandallo4.jpg',
                'group' => 'kandallo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'name' => 'Minimál stílusú modern kandalló mészkőből',
                'image_url' => '/storage/architectures/kandallo5.jpg',
                'group' => 'kandallo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'name' => 'Minimál stílusú modern kandalló mészkőből',
                'image_url' => '/storage/architectures/kandallo6.jpg',
                'group' => 'kandallo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'name' => 'Egyedi tervezésű kandalló River Gold gránitból',
                'image_url' => '/storage/architectures/kandallo7.jpg',
                'group' => 'kandallo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'name' => 'Egyedi tervezésű kandalló River Gold gránitból',
                'image_url' => '/storage/architectures/kandallo8.jpg',
                'group' => 'kandallo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'name' => 'Egyedi tervezésű kandalló River Gold gránitból',
                'image_url' => '/storage/architectures/kandallo9.jpg',
                'group' => 'kandallo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'name' => 'Egyedi tervezésű kandalló River Gold gránitból',
                'image_url' => '/storage/architectures/kandallo10.jpg',
                'group' => 'kandallo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Padlóburkolat
            [
                'order' => 1,
                'name' => 'Klasszikus gránit padlóburkolat',
                'image_url' => '/storage/architectures/padloburkolat1.jpg',
                'group' => 'padloburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'Klasszikus gránit padlóburkolat',
                'image_url' => '/storage/architectures/padloburkolat2.jpg',
                'group' => 'padloburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'Tervezett minta szerinti gránit padlóburkolat',
                'image_url' => '/storage/architectures/padloburkolat3.jpg',
                'group' => 'padloburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'Speciális rajzolatú nagyméretű gránit padlóburkolat',
                'image_url' => '/storage/architectures/padloburkolat4.jpg',
                'group' => 'padloburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'name' => 'Tervezett minta szerinti gránit padlóburkolat',
                'image_url' => '/storage/architectures/padloburkolat5.jpg',
                'group' => 'padloburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'name' => 'Klasszikus gránit padlóburkolat',
                'image_url' => '/storage/architectures/padloburkolat6.jpg',
                'group' => 'padloburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Kültéri burkolat
            [
                'order' => 1,
                'name' => 'Buff Grey Quartzite matt felületű kültéri soros burkolat nagy méretű lapokból',
                'image_url' => '/storage/architectures/kulteriburkolat1.jpg',
                'group' => 'kulteriburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'Durva antikolt gyémántkefélt felületű Steel Grey gránit kültéri burkolat szabályos méretű lapokból',
                'image_url' => '/storage/architectures/kulteriburkolat2.jpg',
                'group' => 'kulteriburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'Égetett felületű Bianco Kinawa gránit kültéri burkolat egyedi lapkiosztással',
                'image_url' => '/storage/architectures/kulteriburkolat3.jpg',
                'group' => 'kulteriburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'Égetett felületű Bianco Kinawa gránit kültéri burkolat egyedi lapkiosztással',
                'image_url' => '/storage/architectures/kulteriburkolat4.jpg',
                'group' => 'kulteriburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'name' => 'Impala és Rosa Beta gránit kültéri burkolat égetett felülettel',
                'image_url' => '/storage/architectures/kulteriburkolat5.jpg',
                'group' => 'kulteriburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'name' => 'Jura Gelb mészkő mattcsiszolt felülettel kültéri burkolat',
                'image_url' => '/storage/architectures/kulteriburkolat6.jpg',
                'group' => 'kulteriburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'name' => 'Jura kevert Jura Beige Jura Grau Jura erezett mészkő kültéri matt felületű burkolat',
                'image_url' => '/storage/architectures/kulteriburkolat7.jpg',
                'group' => 'kulteriburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'name' => 'Matt felületű Jura Grau mészkő kültéri burkolat soros lapkiosztással',
                'image_url' => '/storage/architectures/kulteriburkolat8.jpg',
                'group' => 'kulteriburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'name' => 'Royal Mahogany gránit égetett felületű burkolat és lekerekített szegélykő',
                'image_url' => '/storage/architectures/kulteriburkolat9.jpg',
                'group' => 'kulteriburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'name' => 'Royal Mahogany gránit égetett felületű burkolat és lekerekített szegélykő',
                'image_url' => '/storage/architectures/kulteriburkolat10.jpg',
                'group' => 'kulteriburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Homlokzat burkolat
            [
                'order' => 1,
                'name' => 'Crema Marfil mészkő homlokzat falburkolat',
                'image_url' => '/storage/architectures/homlokzatburkolat1.jpg',
                'group' => 'homlokzatburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'Giallo SF Real GM gránit homlokzat falburkolat',
                'image_url' => '/storage/architectures/homlokzatburkolat2.jpg',
                'group' => 'homlokzatburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'Giallo SF Real MM gránit homlokzat falburkolat',
                'image_url' => '/storage/architectures/homlokzatburkolat3.jpg',
                'group' => 'homlokzatburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'Jura Beige mészkő homlokzat falburkolat',
                'image_url' => '/storage/architectures/homlokzatburkolat4.jpg',
                'group' => 'homlokzatburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'name' => 'Jura erezett mészkő homlokzat falburkolat',
                'image_url' => '/storage/architectures/homlokzatburkolat5.jpg',
                'group' => 'homlokzatburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'name' => 'Jura Gold mészkő homlokzat falburkolat',
                'image_url' => '/storage/architectures/homlokzatburkolat6.jpg',
                'group' => 'homlokzatburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'name' => 'Jura kevert mészkő homlokzat falburkolat',
                'image_url' => '/storage/architectures/homlokzatburkolat7.jpg',
                'group' => 'homlokzatburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'name' => 'King Beige mészkő homlokzat falburkolat és ablakkeret',
                'image_url' => '/storage/architectures/homlokzatburkolat8.jpg',
                'group' => 'homlokzatburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'name' => 'King Beige mészkő homlokzat falburkolat és ajtókeret',
                'image_url' => '/storage/architectures/homlokzatburkolat9.jpg',
                'group' => 'homlokzatburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'name' => 'Travertino Classico és Noce Cut Római Travertin mészkő homlokzat falburkolat',
                'image_url' => '/storage/architectures/homlokzatburkolat10.jpg',
                'group' => 'homlokzatburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 11,
                'name' => 'Travertino Silver mészkő homlokzat falburkolat',
                'image_url' => '/storage/architectures/homlokzatburkolat11.jpg',
                'group' => 'homlokzatburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 12,
                'name' => 'Jura Gelb mészkő pillér oszlopburkolat',
                'image_url' => '/storage/architectures/homlokzatburkolat12.jpg',
                'group' => 'homlokzatburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 13,
                'name' => 'Jura Gelb mészkő homlokzat falburkolat',
                'image_url' => '/storage/architectures/homlokzatburkolat13.jpg',
                'group' => 'homlokzatburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 14,
                'name' => 'Jura Gelb mészkő íves homlokzat falburkolat',
                'image_url' => '/storage/architectures/homlokzatburkolat14.jpg',
                'group' => 'homlokzatburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Medence szegélykő
            [
                'order' => 1,
                'name' => 'Jura Gelb medence szegélykő',
                'image_url' => '/storage/architectures/medenceszegelyko1.jpg',
                'group' => 'medenceszegelyko',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'Jura Grau medence szegélykő',
                'image_url' => '/storage/architectures/medenceszegelyko2.jpg',
                'group' => 'medenceszegelyko',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'Jura Grau tipegő és medence szegélykő',
                'image_url' => '/storage/architectures/medenceszegelyko3.jpg',
                'group' => 'medenceszegelyko',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'King Beige medence szegélykő',
                'image_url' => '/storage/architectures/medenceszegelyko4.jpg',
                'group' => 'medenceszegelyko',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Kőbútor
            [
                'order' => 1,
                'name' => 'Nero Assoluto India gránit dohányzóasztal',
                'image_url' => '/storage/architectures/kobutor1.jpg',
                'group' => 'kobutor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'Nero Assoluto India gránit étkezőasztal',
                'image_url' => '/storage/architectures/kobutor2.jpg',
                'group' => 'kobutor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'Nero Belfast Extra gránit dohányzóasztal',
                'image_url' => '/storage/architectures/kobutor3.jpg',
                'group' => 'kobutor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'Star Galaxy gránit dohányzóasztal',
                'image_url' => '/storage/architectures/kobutor4.jpg',
                'group' => 'kobutor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'name' => 'Black Galaxy gránit dohányzóasztal',
                'image_url' => '/storage/architectures/kobutor5.jpg',
                'group' => 'kobutor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'name' => 'Westberg gránit étkezőasztal',
                'image_url' => '/storage/architectures/kobutor6.jpg',
                'group' => 'kobutor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'name' => 'Olive Green gránit étkezőasztal',
                'image_url' => '/storage/architectures/kobutor7.jpg',
                'group' => 'kobutor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'name' => 'Olive Green gránit dohányzóasztal',
                'image_url' => '/storage/architectures/kobutor8.jpg',
                'group' => 'kobutor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'name' => 'Labrador Emerald Pearl gránit irodai asztal',
                'image_url' => '/storage/architectures/kobutor9.jpg',
                'group' => 'kobutor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'name' => 'Travertin Carpinis mészkő dohányzóasztal',
                'image_url' => '/storage/architectures/kobutor10.jpg',
                'group' => 'kobutor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 11,
                'name' => 'Gránit kerti bútor garnitúra',
                'image_url' => '/storage/architectures/kobutor11.jpg',
                'group' => 'kobutor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 12,
                'name' => 'Star Galaxy gránit telefonasztal',
                'image_url' => '/storage/architectures/kobutor12.jpg',
                'group' => 'kobutor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 13,
                'name' => 'Tardosi mészkő asztali lámpa áttört csavart oszloppal',
                'image_url' => '/storage/architectures/kobutor13.jpg',
                'group' => 'kobutor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 14,
                'name' => 'Tardosi mészkő álló lámpa áttört csavart oszloppal',
                'image_url' => '/storage/architectures/kobutor14.jpg',
                'group' => 'kobutor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 15,
                'name' => 'Ruskicai márvány áttört csavart díszoszlop',
                'image_url' => '/storage/architectures/kobutor15.jpg',
                'group' => 'kobutor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Emlékmű
            [
                'order' => 1,
                'name' => 'A képen látható Kitelepítési emlékmű Bánvölgyi László szobrász tervei alapján készült, Bóly',
                'image_url' => '/storage/architectures/emlekmu1.jpg',
                'group' => 'emlekmu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'A képen látható Kitelepítési emlékmű Bánvölgyi László szobrász tervei alapján készült, Bóly',
                'image_url' => '/storage/architectures/emlekmu2.jpg',
                'group' => 'emlekmu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'A képen látható Kitelepítési emlékmű Bánvölgyi László szobrász tervei alapján készült, Bóly',
                'image_url' => '/storage/architectures/emlekmu3.jpg',
                'group' => 'emlekmu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'A képen látható Kitelepítési emlékmű Bánvölgyi László szobrász tervei alapján készült, Bóly',
                'image_url' => '/storage/architectures/emlekmu4.jpg',
                'group' => 'emlekmu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'name' => '56-os emlékmű, Rákoskeresztúr',
                'image_url' => '/storage/architectures/emlekmu5.jpg',
                'group' => 'emlekmu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'name' => '56-os emlékmű, Rákoskeresztúr',
                'image_url' => '/storage/architectures/emlekmu6.jpg',
                'group' => 'emlekmu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'name' => '56-os emlékmű, Pomáz',
                'image_url' => '/storage/architectures/emlekmu7.jpg',
                'group' => 'emlekmu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'name' => '56-os emlékmű, Pomáz',
                'image_url' => '/storage/architectures/emlekmu8.jpg',
                'group' => 'emlekmu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'name' => '3. Honvéd Huszárezred emlékmű, Szeged, Reök tér',
                'image_url' => '/storage/architectures/emlekmu9.jpg',
                'group' => 'emlekmu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'name' => '3. Honvéd Huszárezred emlékmű, Szeged, Reök tér',
                'image_url' => '/storage/architectures/emlekmu10.jpg',
                'group' => 'emlekmu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 11,
                'name' => '3. Honvéd Huszárezred emlékmű, Szeged, Reök tér',
                'image_url' => '/storage/architectures/emlekmu11.jpg',
                'group' => 'emlekmu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 12,
                'name' => 'Spirál emlékmű, Körmend, Főtér',
                'image_url' => '/storage/architectures/emlekmu12.jpg',
                'group' => 'emlekmu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 13,
                'name' => 'Spirál emlékmű, Körmend, Főtér',
                'image_url' => '/storage/architectures/emlekmu13.jpg',
                'group' => 'emlekmu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 14,
                'name' => 'Spirál emlékmű, Körmend, Főtér',
                'image_url' => '/storage/architectures/emlekmu14.jpg',
                'group' => 'emlekmu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 15,
                'name' => 'A képen látható emlékmű Popovics Lőrinc és Pesti Ferenc szobrászok alkotása',
                'image_url' => '/storage/architectures/emlekmu15.jpg',
                'group' => 'emlekmu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 16,
                'name' => 'A képen látható emlékmű Popovics Lőrinc és Pesti Ferenc szobrászok alkotása',
                'image_url' => '/storage/architectures/emlekmu16.jpg',
                'group' => 'emlekmu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 17,
                'name' => 'A képen látható emlékmű Popovics Lőrinc és Pesti Ferenc szobrászok alkotása',
                'image_url' => '/storage/architectures/emlekmu17.jpg',
                'group' => 'emlekmu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 18,
                'name' => 'A képen látható Jedlik Ányok bronz szobor és kompozíció, Bánvölgyi László szobrász alkotása, Szeged',
                'image_url' => '/storage/architectures/emlekmu18.jpg',
                'group' => 'emlekmu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 19,
                'name' => '56-os emlékmű, Soroksár',
                'image_url' => '/storage/architectures/emlekmu19.jpg',
                'group' => 'emlekmu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 20,
                'name' => 'Iskolai emléktábla, Budapest',
                'image_url' => '/storage/architectures/emlekmu20.jpg',
                'group' => 'emlekmu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 21,
                'name' => 'Szent István emléktábla, a bronzból készült dombormű Zsin Judit szobrászművész alkotása, Szigetszentmiklós',
                'image_url' => '/storage/architectures/emlekmu21.jpg',
                'group' => 'emlekmu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 22,
                'name' => 'Budapart alapkőletétel, Budapest',
                'image_url' => '/storage/architectures/emlekmu22.jpg',
                'group' => 'emlekmu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 23,
                'name' => 'Szent István emléktábla, Hatvan',
                'image_url' => '/storage/architectures/emlekmu23.jpg',
                'group' => 'emlekmu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Szökőkút
            [
                'order' => 1,
                'name' => 'Szent György bronz lovas szobor és ivókút, Bánvölgyi László szobrász alkotása, Bordány, Főtér',
                'image_url' => '/storage/architectures/szokokut1.jpg',
                'group' => 'szokokut',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'Szent György bronz lovas szobor és ivókút, Bánvölgyi László szobrász alkotása, Bordány, Főtér',
                'image_url' => '/storage/architectures/szokokut2.jpg',
                'group' => 'szokokut',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'Szecessziós ivókút, Szeged, Reök tér',
                'image_url' => '/storage/architectures/szokokut3.jpg',
                'group' => 'szokokut',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'Szecessziós ivókút, Szeged, Reök tér',
                'image_url' => '/storage/architectures/szokokut4.jpg',
                'group' => 'szokokut',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'name' => 'Spirál szökőkút, Körmend, Főtér',
                'image_url' => '/storage/architectures/szokokut5.jpg',
                'group' => 'szokokut',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'name' => 'Spirál szökőkút, Körmend, Főtér',
                'image_url' => '/storage/architectures/szokokut6.jpg',
                'group' => 'szokokut',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'name' => 'Spirál szökőkút, Körmend, Főtér',
                'image_url' => '/storage/architectures/szokokut7.jpg',
                'group' => 'szokokut',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'name' => 'Spirál szökőkút, Budapest, telephely, darabokban',
                'image_url' => '/storage/architectures/szokokut8.jpg',
                'group' => 'szokokut',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'name' => 'Spirál szökőkút, Budapest, telephely, alakulóban',
                'image_url' => '/storage/architectures/szokokut9.jpg',
                'group' => 'szokokut',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'name' => 'Spirál szökőkút, Budapest, telephely, forráskő',
                'image_url' => '/storage/architectures/szokokut10.jpg',
                'group' => 'szokokut',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 11,
                'name' => 'Spirál szökőkút, Budapest, telephely, látványában',
                'image_url' => '/storage/architectures/szokokut11.jpg',
                'group' => 'szokokut',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 12,
                'name' => 'Buborék szökőkút, Répcelak, Főtér',
                'image_url' => '/storage/architectures/szokokut12.jpg',
                'group' => 'szokokut',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 13,
                'name' => 'Buborék szökőkút, Répcelak, Főtér',
                'image_url' => '/storage/architectures/szokokut13.jpg',
                'group' => 'szokokut',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 14,
                'name' => 'Buborék szökőkút, Répcelak, Főtér',
                'image_url' => '/storage/architectures/szokokut14.jpg',
                'group' => 'szokokut',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 15,
                'name' => 'Szökőkút',
                'image_url' => '/storage/architectures/szokokut15.jpg',
                'group' => 'szokokut',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 16,
                'name' => 'Ivókút',
                'image_url' => '/storage/architectures/szokokut16.jpg',
                'group' => 'szokokut',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Speciális kőtermék
            [
                'order' => 1,
                'name' => 'Speciális gyártó- és mérő eszközökhöz készült gépasztal gránit tömbböl',
                'image_url' => '/storage/architectures/specialiskotermek1.jpg',
                'group' => 'specialiskotermek',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'Speciális gyártó- és mérő eszközökhöz készült gépasztal gránit tömbböl',
                'image_url' => '/storage/architectures/specialiskotermek2.jpg',
                'group' => 'specialiskotermek',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'Speciális gyártó- és mérő eszközökhöz készült gépasztal gránit tömbböl',
                'image_url' => '/storage/architectures/specialiskotermek3.jpg',
                'group' => 'specialiskotermek',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'Speciális gyártó- és mérő eszközökhöz készült gépasztal gránit tömbböl',
                'image_url' => '/storage/architectures/specialiskotermek4.jpg',
                'group' => 'specialiskotermek',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'name' => 'Minimál stílusban készült Black Galaxy gránit mosdókagyló',
                'image_url' => '/storage/architectures/specialiskotermek5.jpg',
                'group' => 'specialiskotermek',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'name' => 'Minimál stílusban készült Black Galaxy gránit mosdókagyló',
                'image_url' => '/storage/architectures/specialiskotermek6.jpg',
                'group' => 'specialiskotermek',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'name' => 'Minimál stílusban készült Black Galaxy gránit mosdókagyló',
                'image_url' => '/storage/architectures/specialiskotermek7.jpg',
                'group' => 'specialiskotermek',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'name' => 'Minimál stílusban készült Black Galaxy gránit mosdókagyló',
                'image_url' => '/storage/architectures/specialiskotermek8.jpg',
                'group' => 'specialiskotermek',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'name' => 'Márványból készült kolombárium',
                'image_url' => '/storage/architectures/specialiskotermek9.jpg',
                'group' => 'specialiskotermek',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'name' => 'Gránitból készült "tüzérségi lövedék"',
                'image_url' => '/storage/architectures/specialiskotermek10.jpg',
                'group' => 'specialiskotermek',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Lézergravírozás
            [
                'order' => 1,
                'name' => 'Lézergravírozás #1',
                'image_url' => '/storage/architectures/lezergravirozas1.png',
                'group' => 'lezergravirozas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'Lézergravírozás #2',
                'image_url' => '/storage/architectures/lezergravirozas2.png',
                'group' => 'lezergravirozas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'Lézergravírozás #3',
                'image_url' => '/storage/architectures/lezergravirozas3.png',
                'group' => 'lezergravirozas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'Lézergravírozás #4',
                'image_url' => '/storage/architectures/lezergravirozas4.png',
                'group' => 'lezergravirozas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'name' => 'Lézergravírozás #5',
                'image_url' => '/storage/architectures/lezergravirozas5.png',
                'group' => 'lezergravirozas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'name' => 'Lézergravírozás #6',
                'image_url' => '/storage/architectures/lezergravirozas6.png',
                'group' => 'lezergravirozas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'name' => 'Lézergravírozás #7',
                'image_url' => '/storage/architectures/lezergravirozas7.png',
                'group' => 'lezergravirozas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'name' => 'Lézergravírozás #8',
                'image_url' => '/storage/architectures/lezergravirozas8.png',
                'group' => 'lezergravirozas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'name' => 'Lézergravírozás #9',
                'image_url' => '/storage/architectures/lezergravirozas9.png',
                'group' => 'lezergravirozas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
