<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArchitectureSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('architectures')->insert([
            // Konyhapult
            [
                'order' => 1,
                'name' => 'Paradiso Classico gránit',
                'image_url' => '/storage/architectures/konyhapult1.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'Rosso Vanga gránit',
                'image_url' => '/storage/architectures/konyhapult2.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'Rosa Beta gránit',
                'image_url' => '/storage/architectures/konyhapult3.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'Nero Assoluto Indian',
                'image_url' => '/storage/architectures/konyhapult4.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'name' => 'Tiger Skin gránit',
                'image_url' => '/storage/architectures/konyhapult5.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'name' => 'Tiger Skin gránit',
                'image_url' => '/storage/architectures/konyhapult6.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'name' => 'Nero Africa Impala gránit',
                'image_url' => '/storage/architectures/konyhapult7.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'name' => 'Nero Africa Impala gránit',
                'image_url' => '/storage/architectures/konyhapult8.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'name' => 'Verde San Francisco gránit',
                'image_url' => '/storage/architectures/konyhapult9.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'name' => 'Verde San Francisco gránit',
                'image_url' => '/storage/architectures/konyhapult10.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 11,
                'name' => 'Halmstadt gránit',
                'image_url' => '/storage/architectures/konyhapult11.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 12,
                'name' => 'Giallo Veneziano gránit',
                'image_url' => '/storage/architectures/konyhapult12.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 13,
                'name' => 'Giallo Veneziano gránit',
                'image_url' => '/storage/architectures/konyhapult13.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 14,
                'name' => 'Verde Laguna gránit',
                'image_url' => '/storage/architectures/konyhapult14.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 15,
                'name' => 'Verde Laguna gránit',
                'image_url' => '/storage/architectures/konyhapult15.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 16,
                'name' => 'Verde Laguna gránit',
                'image_url' => '/storage/architectures/konyhapult16.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 17,
                'name' => 'Verde Laguna gránit',
                'image_url' => '/storage/architectures/konyhapult17.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 18,
                'name' => 'Verde Laguna gránit',
                'image_url' => '/storage/architectures/konyhapult18.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 19,
                'name' => 'Nero Assoluto Indian gránit',
                'image_url' => '/storage/architectures/konyhapult19.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'order' => 20,
                'name' => 'Nero Assoluto Indian gránit',
                'image_url' => '/storage/architectures/konyhapult20.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 21,
                'name' => 'Nero Assoluto Indian gránit',
                'image_url' => '/storage/architectures/konyhapult21.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 22,
                'name' => 'Nero Assoluto Indian gránit',
                'image_url' => '/storage/architectures/konyhapult22.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 23,
                'name' => 'Giallo Veneziano gránit pult',
                'image_url' => '/storage/architectures/konyhapult23.jpg',
                'group' => 'konyhapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Fürdőszobapult
            [
                'order' => 1,
                'name' => 'Copacabana gránit fürdőszobapult, Hilton Budapest',
                'image_url' => '/storage/architectures/furdoszobapult1.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'Copacabana gránitfürdőszobapult, Hilton Budapest, 3. emelet',
                'image_url' => '/storage/architectures/furdoszobapult2.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'Copacabana gránitfürdőszobapult, Hilton Budapest, 3. emelet',
                'image_url' => '/storage/architectures/furdoszobapult3.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'Copacabana gránit fürdőszobapult, Hilton Budapest',
                'image_url' => '/storage/architectures/furdoszobapult4.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'name' => 'Copacabana gránit fürdőszobapult, Hilton Budapest',
                'image_url' => '/storage/architectures/furdoszobapult5.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'name' => 'Copacabana gránit fürdőszobapult, Hilton Budapest',
                'image_url' => '/storage/architectures/furdoszobapult6.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'name' => 'Schöderhamn gránit közösségi mosdók, Hilton Budapest',
                'image_url' => '/storage/architectures/furdoszobapult7.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'name' => 'Brazulite gránit közösségi mosdók, Hilton Budapest',
                'image_url' => '/storage/architectures/furdoszobapult8.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'name' => 'Schöderhamn gránit közösségi mosdók, Hilton Budapest',
                'image_url' => '/storage/architectures/furdoszobapult9.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'name' => 'Azul Bahia gránit fürdőszobapult, Hilton Budapest, elnöki lakosztály',
                'image_url' => '/storage/architectures/furdoszobapult10.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 11,
                'name' => 'Via Lattea gránit mosdópult',
                'image_url' => '/storage/architectures/furdoszobapult11.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 12,
                'name' => 'Labrador Blue LGHQ gránit fürdőszobapul',
                'image_url' => '/storage/architectures/furdoszobapult12.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 13,
                'name' => 'Nero Assoluto India gránit fürdőkád körüli burkolat',
                'image_url' => '/storage/architectures/furdoszobapult13.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 14,
                'name' => 'Jura Beige mészkő fürdőkád körüli burkolat',
                'image_url' => '/storage/architectures/furdoszobapult14.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 15,
                'name' => 'Azul Bahia gránit fürdőkád körülidíszburkolat, Hilton Budapest, elnöki lakosztály',
                'image_url' => '/storage/architectures/furdoszobapult15.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 16,
                'name' => 'Giallo Veneziano gránit fürdőszobapult',
                'image_url' => '/storage/architectures/furdoszobapult16.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 17,
                'name' => 'Via Lattea gránit fürdőkád körüli burkolat és díszhomlokzat',
                'image_url' => '/storage/architectures/furdoszobapult17.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 18,
                'name' => 'zul Bahia gránit fürdőkád körüli díszburkolat, Hilton Budapest, elnöki lakosztály',
                'image_url' => '/storage/architectures/furdoszobapult18.jpg',
                'group' => 'furdoszobapult',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Lépcsőburkolat
            [
                'order' => 1,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat1.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat2.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat3.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat4.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat5.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat6.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat7.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat8.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat9.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat10.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 11,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat11.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 12,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat12.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 13,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat13.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 14,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat14.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 15,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat15.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 16,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat16.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 17,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat17.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 18,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat18.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 19,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat19.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 20,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat20.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 1,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 1,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 1,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 1,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 1,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 1,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 1,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 1,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 1,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 1,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 1,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 1,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 1,
                'name' => '',
                'image_url' => '/storage/architectures/lepcsoburkolat.jpg',
                'group' => 'lepcsoburkolat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
