<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StoneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('stones')->insert([
            // Anyagtár - Gránit
            [
                'order' => 1,
                'name' => 'African Red',
                'origin' => 'Dél-Afrika',
                'color' => 'Homogén vörös, fekete pikkelyekkel',
                'image_url' => '/storage/stones/anyagtar-granit1.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'Aurora Indian',
                'origin' => 'India',
                'color' => 'Sötétbarna alapon, erőteljes vörösesbarna erekkel',
                'image_url' => '/storage/stones/anyagtar-granit2.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'Baltic Brown',
                'origin' => 'Finnország',
                'color' => 'Homogén barna foltokkal, bézs pöttyökkel',
                'image_url' => '/storage/stones/anyagtar-granit3.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'Baltic Green',
                'origin' => 'Finnország',
                'color' => 'Homogén sötétzöld alapon, egreszöld pikkelyekkel',
                'image_url' => '/storage/stones/anyagtar-granit4.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'name' => 'Bararp',
                'origin' => 'Svédország',
                'color' => 'Homogén barna, fekete haránt csíkokkal',
                'image_url' => '/storage/stones/anyagtar-granit5.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'name' => 'Bros Blue',
                'origin' => 'India',
                'color' => 'Homogén fekete alapon, topázkék pikkelyekkel',
                'image_url' => '/storage/stones/anyagtar-granit6.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'name' => 'Crema Bordeaux',
                'origin' => 'Brazília',
                'color' => 'Homogén pasztel mályva, bézs jódbarna, mozgalmas ekkel',
                'image_url' => '/storage/stones/anyagtar-granit7.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'name' => 'Emerald Black',
                'origin' => 'Norvégia',
                'color' => 'Homogén sötétszürke alapon, holdezüst apró pikkelyekkel',
                'image_url' => '/storage/stones/anyagtar-granit8.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'name' => 'Giallo Ornamentale',
                'origin' => 'Brazília',
                'color' => 'Homogén csontfehér alapon, drapp, bézs szemcsékkel',
                'image_url' => '/storage/stones/anyagtar-granit9.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'name' => 'Giallo Veneziano Fiorito',
                'origin' => 'Brazília',
                'color' => 'Homogén sárga, bézs fekete kontúros pikkelyekkel',
                'image_url' => '/storage/stones/anyagtar-granit10.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 11,
                'name' => 'Himalayan Blue',
                'origin' => 'India',
                'color' => 'Szín	Homogén barna alapon bézs hullámokkal',
                'image_url' => '/storage/stones/anyagtar-granit11.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 12,
                'name' => 'Kinawa Rose',
                'origin' => 'Brazília',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit12.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 13,
                'name' => 'Labrador Blue Antique',
                'origin' => 'Norvégia',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit13.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 14,
                'name' => 'Labrador Blue Pearl GT',
                'origin' => 'Norvégia',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit14.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 15,
                'name' => 'Labrador Emerald Pearl',
                'origin' => 'Norvégia',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit15.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 16,
                'name' => 'Labrador Silver',
                'origin' => 'Norvégia',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit16.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 17,
                'name' => 'Multicolor',
                'origin' => 'India',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit17.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 18,
                'name' => 'Nero Africa Impala',
                'origin' => 'Dél-Afrika',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit18.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 19,
                'name' => 'Nero Assoluto In',
                'origin' => 'India',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit19.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 20,
                'name' => 'Nero Belfast Extra',
                'origin' => 'Dél-Afrika',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit20.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 21,
                'name' => 'Nilo River',
                'origin' => 'Brazília',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit21.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 22,
                'name' => 'Olive Green',
                'origin' => 'Dél-Afrika',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit22.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 23,
                'name' => 'Paradiso Classico',
                'origin' => 'India',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit23.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 24,
                'name' => 'Porto Rosa',
                'origin' => 'Brazília',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit24.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 25,
                'name' => 'Red Gaby',
                'origin' => 'Dél-Afrika',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit25.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 26,
                'name' => 'River Gold',
                'origin' => 'India',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit26.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 27,
                'name' => 'River White',
                'origin' => 'India',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit27.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 28,
                'name' => 'Rosa Beta',
                'origin' => 'Olaszország',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit28.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 29,
                'name' => 'Roso Porrino',
                'origin' => 'Spanyolország',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit29.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 30,
                'name' => 'Rosso Vanga',
                'origin' => 'Svédország',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit30.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 31,
                'name' => 'Saphire Blue',
                'origin' => 'India',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit31.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 32,
                'name' => 'Saphire Brown',
                'origin' => 'India',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit32.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 33,
                'name' => 'Shangrila',
                'origin' => 'Brazília',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit33.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 34,
                'name' => 'Shivakashi',
                'origin' => 'India',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit34.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 35,
                'name' => 'Star Galaxy',
                'origin' => 'India',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit35.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 36,
                'name' => 'Tan Brown',
                'origin' => 'India',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit36.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 37,
                'name' => 'Tarn Claire',
                'origin' => 'Franciaország',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit37.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 38,
                'name' => 'Verde Marina',
                'origin' => 'India',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit38.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 39,
                'name' => 'Verde San Francisco',
                'origin' => 'Brazília',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit39.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 40,
                'name' => 'Verde Tropical',
                'origin' => 'Brazília',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit40.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 41,
                'name' => 'Via Lattea',
                'origin' => 'Brazília',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit41.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 42,
                'name' => 'Vizag Blue',
                'origin' => 'India',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit42.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 43,
                'name' => 'Vyara',
                'origin' => 'India',
                'color' => '',
                'image_url' => '/storage/stones/anyagtar-granit43.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Anyagtár - Márvány
        ]);
    }
}
