<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StoneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('stones')->insert([
            // Anyagtár - Gránit
            [
                'order' => 1,
                'name' => 'African Red',
                'origin' => 'Dél-Afrika',
                'color' => 'Homogén vörös, fekete pikkelyekkel',
                'image_url' => '/storage/stones/anyagtar-granit1.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'Aurora Indian',
                'origin' => 'India',
                'color' => 'Sötétbarna alapon, erőteljes vörösesbarna erekkel',
                'image_url' => '/storage/stones/anyagtar-granit2.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'Baltic Brown',
                'origin' => 'Finnország',
                'color' => 'Homogén barna foltokkal, bézs pöttyökkel',
                'image_url' => '/storage/stones/anyagtar-granit3.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'Baltic Green',
                'origin' => 'Finnország',
                'color' => 'Homogén sötétzöld alapon, egreszöld pikkelyekkel',
                'image_url' => '/storage/stones/anyagtar-granit4.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'name' => 'Bararp',
                'origin' => 'Svédország',
                'color' => 'Homogén barna, fekete haránt csíkokkal',
                'image_url' => '/storage/stones/anyagtar-granit5.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'name' => 'Bros Blue',
                'origin' => 'India',
                'color' => 'Homogén fekete alapon, topázkék pikkelyekkel',
                'image_url' => '/storage/stones/anyagtar-granit6.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'name' => 'Crema Bordeaux',
                'origin' => 'Brazília',
                'color' => 'Homogén pasztel mályva, bézs jódbarna, mozgalmas ekkel',
                'image_url' => '/storage/stones/anyagtar-granit7.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'name' => 'Emerald Black',
                'origin' => 'Norvégia',
                'color' => 'Homogén sötétszürke alapon, holdezüst apró pikkelyekkel',
                'image_url' => '/storage/stones/anyagtar-granit8.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'name' => 'Giallo Ornamentale',
                'origin' => 'Brazília',
                'color' => 'Homogén csontfehér alapon, drapp, bézs szemcsékkel',
                'image_url' => '/storage/stones/anyagtar-granit9.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'name' => 'Giallo Veneziano Fiorito',
                'origin' => 'Brazília',
                'color' => 'Homogén sárga, bézs fekete kontúros pikkelyekkel',
                'image_url' => '/storage/stones/anyagtar-granit10.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 11,
                'name' => 'Himalayan Blue',
                'origin' => 'India',
                'color' => 'Homogén barna alapon bézs hullámokkal',
                'image_url' => '/storage/stones/anyagtar-granit11.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 12,
                'name' => 'Kinawa Rose',
                'origin' => 'Brazília',
                'color' => 'Homogén erezett, szürke, lazac, gyapottfehér erek válltakoznak',
                'image_url' => '/storage/stones/anyagtar-granit12.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 13,
                'name' => 'Labrador Blue Antique',
                'origin' => 'Norvégia',
                'color' => 'Homogén barna alapon bézs pikkelyekkel, fényben kék csillámpikkelyek jelennek meg',
                'image_url' => '/storage/stones/anyagtar-granit13.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 14,
                'name' => 'Labrador Blue Pearl GT',
                'origin' => 'Norvégia',
                'color' => 'Sötétkék alapon csillámkék pikkelyekkel',
                'image_url' => '/storage/stones/anyagtar-granit14.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 15,
                'name' => 'Labrador Emerald Pearl',
                'origin' => 'Norvégia',
                'color' => 'Homogén sötétszürke alapon, hamuszürke foltokkal, türkizzöld csillámpikkelyekkel',
                'image_url' => '/storage/stones/anyagtar-granit15.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 16,
                'name' => 'Labrador Silver',
                'origin' => 'Norvégia',
                'color' => 'Világosszürke alapon, kagylóezüst pikkelyekkel',
                'image_url' => '/storage/stones/anyagtar-granit16.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 17,
                'name' => 'Multicolor',
                'origin' => 'India',
                'color' => 'Világosabb tonusú vörös erezettel',
                'image_url' => '/storage/stones/anyagtar-granit17.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 18,
                'name' => 'Nero Africa Impala',
                'origin' => 'Dél-Afrika',
                'color' => 'Homogén sötétszürke alapon, hamuszürke apró szemcsékkel',
                'image_url' => '/storage/stones/anyagtar-granit18.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 19,
                'name' => 'Nero Assoluto In',
                'origin' => 'India',
                'color' => 'Abszolut homogén fekete',
                'image_url' => '/storage/stones/anyagtar-granit19.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 20,
                'name' => 'Nero Belfast Extra',
                'origin' => 'Dél-Afrika',
                'color' => 'Homogén fekete pici csillámszemcsékkel',
                'image_url' => '/storage/stones/anyagtar-granit20.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 21,
                'name' => 'Nilo River',
                'origin' => 'Brazília',
                'color' => 'Felhős bézs, drapp, mályva foltokkal, sárga erekkel',
                'image_url' => '/storage/stones/anyagtar-granit21.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 22,
                'name' => 'Olive Green',
                'origin' => 'Dél-Afrika',
                'color' => 'Homogén világoszöld alapon, fekete foltokkal',
                'image_url' => '/storage/stones/anyagtar-granit22.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 23,
                'name' => 'Paradiso Classico',
                'origin' => 'India',
                'color' => 'Homogén meggybordó, fekete szemcsékkel',
                'image_url' => '/storage/stones/anyagtar-granit23.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 24,
                'name' => 'Porto Rosa',
                'origin' => 'Brazília',
                'color' => 'Fekete alapon, rózsa és galambszürke hullámokkal, foltokkal',
                'image_url' => '/storage/stones/anyagtar-granit24.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 25,
                'name' => 'Red Gaby',
                'origin' => 'Dél-Afrika',
                'color' => 'Homogén elszórtan fekete, szürke szemcsékkel',
                'image_url' => '/storage/stones/anyagtar-granit25.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 26,
                'name' => 'River Gold',
                'origin' => 'India',
                'color' => 'Törtfehér alapon bézs és sárga hullámokkal',
                'image_url' => '/storage/stones/anyagtar-granit26.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 27,
                'name' => 'River White',
                'origin' => 'India',
                'color' => 'Homogén törtfehér, apró szemcsékkel',
                'image_url' => '/storage/stones/anyagtar-granit27.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 28,
                'name' => 'Rosa Beta',
                'origin' => 'Olaszország',
                'color' => 'Homogén halványrózsa, szürke, fehér pöttyökkel',
                'image_url' => '/storage/stones/anyagtar-granit28.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 29,
                'name' => 'Roso Porrino',
                'origin' => 'Spanyolország',
                'color' => 'Homogén rózsa, szürke, fehér pöttyökkel',
                'image_url' => '/storage/stones/anyagtar-granit29.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 30,
                'name' => 'Rosso Vanga',
                'origin' => 'Svédország',
                'color' => 'Homogén fekete pöttyökkel',
                'image_url' => '/storage/stones/anyagtar-granit30.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 31,
                'name' => 'Saphire Blue',
                'origin' => 'India',
                'color' => 'Homogén barna nagyobb, kék és fekete kisebb pikkelyekkel',
                'image_url' => '/storage/stones/anyagtar-granit31.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 32,
                'name' => 'Saphire Brown',
                'origin' => 'India',
                'color' => 'Homogén sötét alapon bézs és halványkék pikkelyekkel',
                'image_url' => '/storage/stones/anyagtar-granit32.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 33,
                'name' => 'Shangrila',
                'origin' => 'Brazília',
                'color' => 'Erezett, bordó alapon sötétszürke, halványszürke erekkel, csontű pikkelyekkel',
                'image_url' => '/storage/stones/anyagtar-granit33.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 34,
                'name' => 'Shivakashi',
                'origin' => 'India',
                'color' => 'Halványrózsa bordó, bézs haránt futó foltokkal',
                'image_url' => '/storage/stones/anyagtar-granit34.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 35,
                'name' => 'Star Galaxy',
                'origin' => 'India',
                'color' => 'Homogén fekete alapon arany pikkelyekkel',
                'image_url' => '/storage/stones/anyagtar-granit35.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 36,
                'name' => 'Tan Brown',
                'origin' => 'India',
                'color' => 'Homogén barna, sötétbézs nagyobb pikkelyekkel',
                'image_url' => '/storage/stones/anyagtar-granit36.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 37,
                'name' => 'Tarn Claire',
                'origin' => 'Franciaország',
                'color' => 'Homogén szürke, fekete szemcsékkel',
                'image_url' => '/storage/stones/anyagtar-granit37.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 38,
                'name' => 'Verde Marina',
                'origin' => 'India',
                'color' => 'Világoszöld alapon fehér és sötétzöld erekkel',
                'image_url' => '/storage/stones/anyagtar-granit38.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 39,
                'name' => 'Verde San Francisco',
                'origin' => 'Brazília',
                'color' => 'Erezett cédruszöld, és halványzöld foltokkal',
                'image_url' => '/storage/stones/anyagtar-granit39.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 40,
                'name' => 'Verde Tropical',
                'origin' => 'Brazília',
                'color' => 'Erezett smaragzöld, világoszöld, pecsétvörös foltokkal',
                'image_url' => '/storage/stones/anyagtar-granit40.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 41,
                'name' => 'Via Lattea',
                'origin' => 'Brazília',
                'color' => 'Sötétszürke alapon, apró fehér pöttyökkel, elmosódott nagyobb foltokkal',
                'image_url' => '/storage/stones/anyagtar-granit41.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 42,
                'name' => 'Vizag Blue',
                'origin' => 'India',
                'color' => 'Halványkék, fekete erezettel borostyánű pöttyökkel',
                'image_url' => '/storage/stones/anyagtar-granit42.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 43,
                'name' => 'Vyara',
                'origin' => 'India',
                'color' => 'Felhős bézs, drapp, bordó foltokkal',
                'image_url' => '/storage/stones/anyagtar-granit43.jpg',
                'group' => 'anyagtar-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Anyagtár - Márvány
            [
                'order' => 1,
                'name' => 'Ruskica Orange',
                'origin' => 'Románia',
                'color' => 'Törtfehér alapon szürke erekkel, halványbézs foltokkal',
                'image_url' => '/storage/stones/anyagtar-marvany1.jpg',
                'group' => 'anyagtar-marvany',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'Ruskica Pink',
                'origin' => 'Románia',
                'color' => 'Rózsa alapon halvány grafitszürke erekkel, és erőteljesebb szürke erekkel',
                'image_url' => '/storage/stones/anyagtar-marvany2.jpg',
                'group' => 'anyagtar-marvany',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'Ruskica Pink Light',
                'origin' => 'Románia',
                'color' => 'Fehér és halványrózsa alapon galambszürke erekkel',
                'image_url' => '/storage/stones/anyagtar-marvany3.jpg',
                'group' => 'anyagtar-marvany',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'Ruskica Yellowish',
                'origin' => 'Románia',
                'color' => 'Törtfehér alapon halványszürke vékony erekkel',
                'image_url' => '/storage/stones/anyagtar-marvany4.jpg',
                'group' => 'anyagtar-marvany',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'name' => 'Ruskica Yellowish White',
                'origin' => 'Románia',
                'color' => 'Homogén sárgába hajló fehér',
                'image_url' => '/storage/stones/anyagtar-marvany5.jpg',
                'group' => 'anyagtar-marvany',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Anyagtár - Mészkő
            [
                'order' => 1,
                'name' => 'Jura Beige',
                'origin' => 'Németország',
                'color' => 'Bézs alapon sötétebb foltokkal',
                'image_url' => '/storage/stones/anyagtar-meszko1.jpg',
                'group' => 'anyagtar-meszko',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'Jura erezett',
                'origin' => 'Németország',
                'color' => 'Halványbézs alapon pecsétvörös erezettel, fossziliákkal',
                'image_url' => '/storage/stones/anyagtar-meszko2.jpg',
                'group' => 'anyagtar-meszko',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'Jura Grau',
                'origin' => 'Németország',
                'color' => 'Gémszürke alapon bézs, kristálykék pikkelyekkel, szürke kontúrú fossziliákkal',
                'image_url' => '/storage/stones/anyagtar-meszko3.jpg',
                'group' => 'anyagtar-meszko',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'Jura kevert',
                'origin' => 'Németország',
                'color' => 'Mézsárga és drapp színek keverve, barna pikkelyekkel',
                'image_url' => '/storage/stones/anyagtar-meszko4.jpg',
                'group' => 'anyagtar-meszko',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'name' => 'Baschioi',
                'origin' => 'Románia',
                'color' => 'Homogén bézs keverve drapp szemcsével',
                'image_url' => '/storage/stones/anyagtar-meszko5.jpg',
                'group' => 'anyagtar-meszko',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'name' => 'Podeni',
                'origin' => 'Románia',
                'color' => 'Világos bézs alapon halvány drapp szemcsék',
                'image_url' => '/storage/stones/anyagtar-meszko6.jpg',
                'group' => 'anyagtar-meszko',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'name' => 'Travertin Carpinis',
                'origin' => 'Románia',
                'color' => 'Bézs alapon halványbordó csíkokkal, elszórtan világosbarna pikkelyekkel',
                'image_url' => '/storage/stones/anyagtar-meszko7.jpg',
                'group' => 'anyagtar-meszko',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'name' => 'Travertin Geoagiu',
                'origin' => 'Románia',
                'color' => 'Mályvás-bézs alapon kisebb szabálytalan alakú lyukakkal',
                'image_url' => '/storage/stones/anyagtar-meszko8.jpg',
                'group' => 'anyagtar-meszko',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Fehér gránit
            [
                'order' => 1,
                'name' => 'Bianco Antico',
                'origin' => 'Brazília',
                'color' => 'Törtfehér alapon sötétszürke, fekete foltokkal',
                'image_url' => '/storage/stones/feher-granit1.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'Bianco Crystal',
                'origin' => 'Spanyolország',
                'color' => 'Homogén, törtfehér alapon szürke, fekete kisebb-nagyobb szemcsékkel',
                'image_url' => '/storage/stones/feher-granit2.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'Bianco Dalmata',
                'origin' => 'Brazília',
                'color' => 'Homogén, törtfehér alapon szürke, fekete, drapp szemcsékkel',
                'image_url' => '/storage/stones/feher-granit3.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'Bianco Kinawa',
                'origin' => 'Brazília',
                'color' => 'Fehér alapon szürkés fekete erezetű, halvány rózsaszín foltokkal',
                'image_url' => '/storage/stones/feher-granit4.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'name' => 'Bianco Romano',
                'origin' => 'Brazília',
                'color' => 'Törtfehér felhős szürkés erezettel, bordó foltokkal',
                'image_url' => '/storage/stones/feher-granit5.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'name' => 'Bianco Vena Quartzite',
                'origin' => 'Brazília',
                'color' => 'Csontfehér határozott erezetű, halványbarna csíkokkal',
                'image_url' => '/storage/stones/feher-granit6.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'name' => 'Cream Violet',
                'origin' => 'Brazília',
                'color' => 'Homogén, csontfehér alapon meggybordó pöttyökkel',
                'image_url' => '/storage/stones/feher-granit7.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'name' => 'Cristallo Quartzite',
                'origin' => 'Brazília',
                'color' => 'Fehér alapon rozsdavörös foltokkal, jégszerű mintázattal',
                'image_url' => '/storage/stones/feher-granit8.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'name' => 'Delicatus White',
                'origin' => 'Brazília',
                'color' => 'Törtfehér alapon nagyméretű sötétszürke cirmokkal',
                'image_url' => '/storage/stones/feher-granit9.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'name' => 'Delicatus White IB',
                'origin' => 'Brazília',
                'color' => 'Törtfehér alapon fekete, szürke, drapp foltokkal',
                'image_url' => '/storage/stones/feher-granit10.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 11,
                'name' => 'Fantastic White',
                'origin' => 'Brazília',
                'color' => 'Fehér szürke alapon bézs foltokkal',
                'image_url' => '/storage/stones/feher-granit11.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 12,
                'name' => 'Ice Flake Quartzite',
                'origin' => 'Brazília',
                'color' => 'Kékesfehér alapon jégszerű mintázattal',
                'image_url' => '/storage/stones/feher-granit12.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 13,
                'name' => 'Ice Pearl Labrador White',
                'origin' => 'Madagaszkár',
                'color' => 'Törtfehér alapon kisebb-nagyobb szürke, fekete szemcsékkel, elszórtan kék pikkelyekkel',
                'image_url' => '/storage/stones/feher-granit13.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 14,
                'name' => 'Iceberg Quartzite',
                'origin' => 'Brazília',
                'color' => 'Törtfehér, barna halvány erezettel',
                'image_url' => '/storage/stones/feher-granit14.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 15,
                'name' => 'Ivory White',
                'origin' => 'India',
                'color' => 'Homogén fehér alapon apró bordó szemcsékkel, egy-egy szürke erezettel',
                'image_url' => '/storage/stones/feher-granit15.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 16,
                'name' => 'Kashmire White',
                'origin' => 'India',
                'color' => 'Homogén fehér alapon apró szürkés, nagyobb bordó pöttyökkel',
                'image_url' => '/storage/stones/feher-granit16.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 17,
                'name' => 'Krystallys',
                'origin' => 'Brazília',
                'color' => 'Fehér, borostyán színű kristályokkal',
                'image_url' => '/storage/stones/feher-granit17.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 18,
                'name' => 'Luce Di Luna Quartzite',
                'origin' => 'Brazília',
                'color' => 'Fehér felhős, halványszürke erezettel',
                'image_url' => '/storage/stones/feher-granit18.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 19,
                'name' => 'Meera White',
                'origin' => 'India',
                'color' => 'Homogén, törtfehér, szürkés drapp szemcsékkel',
                'image_url' => '/storage/stones/feher-granit19.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 20,
                'name' => 'New Bionco Romano',
                'origin' => 'Brazília',
                'color' => 'Homogén szürke háttér fehérbe hajló foltokkal, halványszürke erezettel',
                'image_url' => '/storage/stones/feher-granit20.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 21,
                'name' => 'River White',
                'origin' => 'India',
                'color' => 'Homogén törtfehér, apró szemcsékkel',
                'image_url' => '/storage/stones/feher-granit21.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 22,
                'name' => 'Shooting Star',
                'origin' => 'Brazília',
                'color' => 'Fehér alapon méz színű erezettel',
                'image_url' => '/storage/stones/feher-granit22.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 23,
                'name' => 'Summer White',
                'origin' => 'Brazília',
                'color' => 'Felhős szürke pöttyökkel',
                'image_url' => '/storage/stones/feher-granit23.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 24,
                'name' => 'Taj Mahal Quartzite',
                'origin' => 'Brazília',
                'color' => 'Felhősen erezett, bézs csíkokkal',
                'image_url' => '/storage/stones/feher-granit24.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 25,
                'name' => 'Tarn Claire',
                'origin' => 'Franciaország',
                'color' => 'Homogén szürke, fekete szemcsékkel',
                'image_url' => '/storage/stones/feher-granit25.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 26,
                'name' => 'Viscont White',
                'origin' => 'India',
                'color' => 'Felhős apró fekete pöttyökkel',
                'image_url' => '/storage/stones/feher-granit26.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 27,
                'name' => 'White Palmas',
                'origin' => 'Brazília',
                'color' => 'Fehér alapon, halványzöld foltokkal, fekete szemcsékkel',
                'image_url' => '/storage/stones/feher-granit27.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 28,
                'name' => 'White Silver',
                'origin' => 'Portugália',
                'color' => 'Homogén fekete szemcsékkel',
                'image_url' => '/storage/stones/feher-granit28.jpg',
                'group' => 'feher-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Sárga gránit
            [
                'order' => 1,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit1.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit2.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit3.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit4.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit5.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit6.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit7.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit8.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit9.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit10.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 11,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit11.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 12,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit12.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 13,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit13.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 14,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit14.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 15,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit15.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 16,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit16.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 17,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit17.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 18,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit18.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 19,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit19.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 20,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit20.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 21,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit21.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 22,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit22.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 23,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit23.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 24,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit24.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 25,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit25.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 26,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit26.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 27,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit27.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 28,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit28.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 29,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit29.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 30,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit30.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 31,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit31.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 32,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit32.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 33,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit33.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 34,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit34.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 35,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit35.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 36,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit36.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 37,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit37.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 38,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit38.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 39,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit39.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 40,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit40.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 41,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit41.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 42,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit42.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 43,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit43.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 44,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit44.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 45,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit45.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 46,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit46.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 47,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit47.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 48,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit48.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 49,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit49.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 50,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit50.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 51,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit51.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 52,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit52.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 53,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit53.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 54,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit54.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 55,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit55.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 56,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit56.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 57,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit57.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 58,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit58.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 59,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit59.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 60,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit60.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 61,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit61.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 62,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit62.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 63,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit63.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 64,
                'name' => 'asd',
                'origin' => '',
                'color' => '',
                'image_url' => '/storage/stones/sarga-granit64.jpg',
                'group' => 'sarga-granit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
