<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UrnaTombstoneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('urna_tombstones')->insert([
            // Urna sírkő 1. csoport
            [
                'order' => 1,
                'tombstone_id' => 'U 32',
                'name' => 'gránit Tarn Claire',
                'description' => 'A burkolt járdaszegélyen 10 cm magasítás, rajta egy 5 cm vastag, nagy fedlap kapott helyet. A fedlapra, kis kivágást és egy süllyesztett vázát helyeztünk. Az emlék formája, régi tradíciókat elevenít fel. A világos gránitra fekete karakterek és kereszt került.',
                'image_name' => 'U32.jpg',
                'group' => 'Urna sírkő 1. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'tombstone_id' => 'U 33',
                'name' => 'gránit Nero Impala',
                'description' => 'Az egész síremlék letisztult minimál stílusban készült. A műkő járdaszegélyre 5 cm vastag nagy fedlap lett helyezve. Rajta kapott helyet egy virág motívum, és egy süllyesztett váza. Az emlék formája, régi tradíciókat elevenít fel.',
                'image_name' => 'U33.jpg',
                'group' => 'Urna sírkő 1. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'tombstone_id' => 'U 71',
                'name' => 'gránit Aurora',
                'description' => 'A műkő járdaszegélyen 5x10 cm szegélykeret kapott helyet, ami nyitott. A lépcső és az emlék amorf és sprengelt. A fózolt váza külön kiemelést kapott. Természetes és naturalisztikus hatást kelt.',
                'image_name' => 'U71.jpg',
                'group' => 'Urna sírkő 1. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'tombstone_id' => 'U 61',
                'name' => 'mészkő Jura Gelb',
                'description' => 'A földre helyezett natur szikla az egyszerű tisztaságot, a természet közelségét és szeretetét sugározza.',
                'image_name' => 'U61.jpg',
                'group' => 'Urna sírkő 1. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'tombstone_id' => 'U 1',
                'name' => 'gránit Tarn Claire',
                'description' => 'Az egész síremlék letisztult minimál stílusban készült. A burkolt járdaszegélyre 5 cm vastag nagy fedlap került. Az emlék egy álló hasáb, arany felirattal díszítve.',
                'image_name' => 'U1.jpg',
                'group' => 'Urna sírkő 1. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'tombstone_id' => 'U 5',
                'name' => 'gránit Nero Assoluto India',
                'description' => 'A műkő járdaszegélyen 10 cm-es magasítás, rajta 3 cm vastag, nagy fedlap kapott helyet. A felirat a fedlapra került, így a könyvnek csak szimbólikus jelentése maradt.',
                'image_name' => 'U5.jpg',
                'group' => 'Urna sírkő 1. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'tombstone_id' => 'U 2',
                'name' => 'gránit Nero Assoluto India',
                'description' => 'Az egész síremlék letisztult, minimál stílusban készült. A műkő járdaszegélyen 5 cm vastag, nagy fedlap kapott helyet. Az emlék formája, régi tradíciókat elevenít fel.',
                'image_name' => 'U2.jpg',
                'group' => 'Urna sírkő 1. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'tombstone_id' => 'U 3',
                'name' => 'gránit Aurora',
                'description' => 'A műkő járdaszegélyen 5x10 cm szegélykeret kapott helyet, ami nyitott. A lépcső és az emlék amorf és sprengelt. Természetes és naturalisztikus hatást kelt.',
                'image_name' => 'U3.jpg',
                'group' => 'Urna sírkő 1. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Urna sírkő 2. csoport
            [
                'order' => 1,
                'tombstone_id' => 'U 24',
                'name' => 'gránit Rosso Vanga',
                'description' => 'Az 5 cm vastag, tömb fedlap közvetlenül a burkolt járdaszegélyre lett helyezve. Az emlék formája régi tradíciókat elevenít fel, felirata aranyozott.',
                'image_name' => 'U24.jpg',
                'group' => 'Urna sírkő 2. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'tombstone_id' => 'U 51',
                'name' => 'gránit Juparana Columbo',
                'description' => 'A burkolt járdaszegélyen 10 cm-es magasítás, rajta egy 3 cm vastag, nagy fedlap helyezkedik el. A sűllyesztett vázák gránit gyűrűből készültek. Az emlék élébe faragott, stilizált "fa" felülete antikolt, a jobb vizuális hatás érdekében.',
                'image_name' => 'U51.jpg',
                'group' => 'Urna sírkő 2. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'tombstone_id' => 'U 69',
                'name' => 'gránit Pannon Grün',
                'description' => 'Közvetlen a burkolt járdaszegélyen kapott helyet egy 5cm vastag tömb fedlap. Az emlék helyett egy naturisztikus oszlopot készítettünk, amin egy porcelán fénykép látható. Anyagából készítettünk egy süllyesztett vázát, a felirat a fedlapra került.',
                'image_name' => 'U69.jpg',
                'group' => 'Urna sírkő 2. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'tombstone_id' => 'U 8',
                'name' => 'gránit Verde Laguna',
                'description' => 'A burkolt járdaszegélyen 10 cm-es magasítás, rajta egy 5 cm vastag, sprengelt, szakított oldalú, nagy fedlap kapott helyet. Az emlék formája naturális, ami tükröz némi természetességet.',
                'image_name' => 'U8.jpg',
                'group' => 'Urna sírkő 2. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'tombstone_id' => 'U 52',
                'name' => 'gránit Baltic Green',
                'description' => 'Közvetlen a burkolt járdaszegélyen kapott helyet egy 5 cm vastag, tömb fedlap. Az emlék formája, régi tradíciókat elevenít fel, a felirat aranyozott. A síremléket vésett aranyozott horgászbot díszíti, ami utal az elhunyt hobbijára.',
                'image_name' => 'U52.jpg',
                'group' => 'Urna sírkő 2. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'tombstone_id' => 'U 27',
                'name' => 'gránit Juparana Columbo',
                'description' => 'A burkolt járdaszegélyre egy 10 cm magas álló szegélykeretet helyeztünk. A fedetlen rész élő virág beültetésére alkalmas. Az emlék egy un. "fejpárna", amire bronz felirat került.',
                'image_name' => 'U27.jpg',
                'group' => 'Urna sírkő 2. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'tombstone_id' => 'U 63',
                'name' => 'gránit Rosso Santiago',
                'description' => 'A burkolt járdaszegélyen 10 cm-es magasítás, azon pedig egy 3 cm vastag, nagy fedlap került elhelyezésre. Az emlék két részből áll. Egy karcsúsított oszlopból és egy hozzá igazodó, enyhe ívű emlékből. A két kő szerves egységet képez.',
                'image_name' => 'U63.jpg',
                'group' => 'Urna sírkő 2. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'tombstone_id' => 'U 65',
                'name' => 'gránit Rosso Santiago',
                'description' => 'A burkolt járdaszegélyen 10 cm-es magasítás, rajta egy 3 cm vastag, nagy fedlap kapott helyet. Az emléket kiemeli a kis lépcső. Az emlék formáját "izgalmassá" teszik a faltz és a legyezők hullámzása.',
                'image_name' => 'U65.jpg',
                'group' => 'Urna sírkő 2. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'tombstone_id' => 'U 66',
                'name' => 'gránit Rosso Santiago',
                'description' => 'A burkolt járdaszegélyen 10cm-es magasítás, rajta pedig egy 3 cm vastag, nagy fedlap kapott helyet. Az emléket kiemeli a kis lépcső. Az emlék formáját "izgalmassá" teszik a faltz és a legyezők hullámzása.',
                'image_name' => 'U66.jpg',
                'group' => 'Urna sírkő 2. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'tombstone_id' => 'U 7',
                'name' => 'gránit Verde San Francisco',
                'description' => 'A burkolt járdaszegélyre ferdére vágott tömb fedlapot helyeztünk. A fedlap végében hagyott platnin bronz kiegészítők kaptak helyet. Az emlék nélkül készült urna síremlék egyszerűségében magával ragadó.',
                'image_name' => 'U7.jpg',
                'group' => 'Urna sírkő 2. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 11,
                'tombstone_id' => 'U 28',
                'name' => 'gránit Nero Assoluto India',
                'description' => 'A műkő járdaszegélyen 5x10 cm-es, nyitott, fekvő szegélykeret látható. A fedetlen rész élő virág beültetésére alkalmas. Az emléknek csak a teteje íves, hogy megtörje az egyenes síkok egyhangúságát.',
                'image_name' => 'U28.jpg',
                'group' => 'Urna sírkő 2. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 12,
                'tombstone_id' => 'U 9',
                'name' => 'gránit Nero Impala',
                'description' => 'A nyitott, műkő járdaszegélyen egy 5 cm vastag, íves elejű fedlap látható, élő virágnak helyet hagyva. A fedlap "könnyű" íveit követi az emlék, amire bronz felirat került.',
                'image_name' => 'U9.jpg',
                'group' => 'Urna sírkő 2. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 13,
                'tombstone_id' => 'U 53',
                'name' => 'gránit Vizag Blue',
                'description' => 'A burkolt járdaszegélyen egy 10 cm magas, álló szegélykeret került elhelyezésre. A fedetlen rész élő virág beültetésére alkalmas. A minimál stílusú emléknek nem a formája különleges, hanem amit hordoz. Mary Zsuzsi síremléke.',
                'image_name' => 'U53.jpg',
                'group' => 'Urna sírkő 2. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 14,
                'tombstone_id' => 'U 55',
                'name' => 'gránit Halmstadt-Bararp',
                'description' => 'A teljesen fedett járdán csak egy szimbolikus nyitott könyv és egy fózolt gránit váza kapott helyet. A könyv lapjába beíródott filmszalag, sok mindent elárul.',
                'image_name' => 'U55.jpg',
                'group' => 'Urna sírkő 2. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 15,
                'tombstone_id' => 'U 60',
                'name' => 'gránit Halmstadt-Bararp',
                'description' => 'A teljesen fedett járdán csak egy szimbolikus nyitott könyv és egy sülyesztett gránit váza kapott helyet. A nyitott könyv rendhagyó választás, erőteljes jelentéssel bír.',
                'image_name' => 'U60.jpg',
                'group' => 'Urna sírkő 2. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 16,
                'tombstone_id' => 'U 4',
                'name' => 'gránit Verde Marina - Black Ebony',
                'description' => 'A burkolt járdaszegélyen 5 cm-es magasítás áll, rajta a 3 cm vastag, nagy fedlap. Az esztergált váza az alsó részre lett helyezve, hogy ne takarja az emléket. Az emlék, párhuzamos oldalakkal és hullámos, zászlós tetővel készült.',
                'image_name' => 'U4.jpg',
                'group' => 'Urna sírkő 2. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 17,
                'tombstone_id' => 'U 45',
                'name' => 'gránit Rosso Vanga',
                'description' => 'A burkolt járdaszegélyre egy ferdére vágott tömb fedlap került, melynek oldala sprengelt. A fedlap elejébe fúrt lyuk alkalmas kis váza elhelyezésére. Az emlék nélkül készült urna síremlék  egyszerű, letisztult.',
                'image_name' => 'U45.jpg',
                'group' => 'Urna sírkő 2. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Urna sírkő 3. csoport
            [
                'order' => 1,
                'tombstone_id' => 'U 64',
                'name' => 'gránit Rosso Vanga',
                'description' => 'A burkolt gránit járdaszegélyen fekszik egy 5 cm vastag, íves elejű fedlap. A bal alsó ívben kapott helyet a süllyesztett váza. Az emlékbe faragott gömbölyded tagozat, meghatározza az emlék karakteres formáját.',
                'image_name' => 'U64.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'tombstone_id' => 'U 50',
                'name' => 'gránit Nero Assoluto India',
                'description' => 'A burkolt járdaszegélyen 10 cm-es magasítás, rajta egy 3 cm vastag, nagy fedlap. Az emlékbe faragott galamb elkészítése, szobrász tudást igényel.',
                'image_name' => 'U50.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'tombstone_id' => 'U 35',
                'name' => 'gránit Rosso Vanga',
                'description' => 'A burkolt járdaszegélyen egy 6 cm vastag, íves elejű fedlap látható. A járdán hagyott ívben kapott helyet a süllyesztett váza. A nyitott könyv rendhagyó választás, erőteljes jelentéssel bír.',
                'image_name' => 'U35.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'tombstone_id' => 'U 70',
                'name' => 'gránit River White',
                'description' => 'A burkolt járdaszegélyen 10 cm-es magasítás, rajta egy 3 cm vastag, nagy fedlap kapott helyet. Az emléket kiemeli a kis lépcső. Az emlék formáját "izgalmassá" teszik a faltz és a legyezők hullámzása.',
                'image_name' => 'U70.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'tombstone_id' => 'U 75',
                'name' => 'gránit Aurora',
                'description' => 'A burkolt járdaszegélyen 10 cm-es magasítás, rajta egy 5 cm vastag, élkerekített nagy fedlap. Az emlékbe faragott rózsa elkészítése szobrász tudást igényel.',
                'image_name' => 'U75.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'tombstone_id' => 'U 59',
                'name' => 'gránit Verde Laguna',
                'description' => 'A burkolt járdaszegélyre egy 10 cm magas szegélykeret került, amire egy 3 cm vastag, kis fedlapot helyeztünk. A gránitból készült, ívfózolt váza az alsó részen kapott helyet, hogy a virág ne takarja az emléket. Az emlék két darabból készült. A közöttük maradt formát látványosabbá teszi a mozgalmas fózni.',
                'image_name' => 'U59.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'tombstone_id' => 'U 56',
                'name' => 'gránit Rosso Vanga',
                'description' => 'A burkolt járdaszegélyen áll a 10 cm-es magasítás, rajta a 3 cm vastag, nagy fedlap. A süllyesztett váza az alsó részre lett helyezve, hogy a virág ne takarja az emléket. Az emlék formáját "izgalmassá" teszi a falz és legyezők hullámzása, ami körbe öleli a formát.',
                'image_name' => 'U56.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'tombstone_id' => 'U 54',
                'name' => 'gránit River Gold',
                'description' => 'A  gránittal burkolt járdaszegélyen fekszik egy 7 cm vastag, íves elejű fedlap. A bal alsó ívben kapott helyet a bronz, süllyesztett váza. A fedlap "könnyű" íveit követi az emlék, amire arany felirat került. Az oldalak un. sprengelt  technológiával készültek.',
                'image_name' => 'U54.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'tombstone_id' => 'U 72',
                'name' => 'márvány Ruskicai',
                'description' => 'A burkolt járdaszegélyen a 10 cm-es magasítás, rajta a 3 cm vastag, nagy fedlap. Az anyagából elkészített 2 db sűllyesztett váza átlósan lett helyezve a fedlapon. Az emlék formáját a könnyed ívek és a nyers gömbölyded tagozatok teszik mozgalmassá.',
                'image_name' => 'U72.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'tombstone_id' => 'U 58',
                'name' => 'gránit Nero Impala',
                'description' => 'A burkolt járdaszegélyen 10 cm-es magasítás, rajta a 3 cm vastag, nagy fedlap kapott helyet. A gránitból készült szögletes süllyesztett váza az alsó részre lett helyezve, hogy a virág ne takarja az emléket. Az emlék formáját könnyed ívek alkotják, csak a nyers fózni teszi karakteressé.',
                'image_name' => 'U58.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 11,
                'tombstone_id' => 'U 67',
                'name' => 'gránit Aurora',
                'description' => 'A burkolt járdaszegélyen a 10 cm-es magasítás, rajta a 3 cm vastag, nagy fedlap. A fózolt váza az alsó részre lett helyezve, hogy a váza és a virág ne takarja az emléket. Az emlék formáját a könnyed ívek és a nyers gömbölyded tagozatok teszik mozgalmassá.',
                'image_name' => 'U67.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 12,
                'tombstone_id' => 'U 68',
                'name' => 'gránit River Gold',
                'description' => 'A burkolt járdaszegélyen fekszik a 10x5cm szegélykeret. A kisfedlapra helyezett gyűrű és betét, süllyesztett vázaként funkcionál. Az emlék, egy lépcsős nyers falcal készült, fekete karakterekkel és kereszttel. Az egész síremlék felülete anikolt, gyémántkefélt, ami ennél a gránitnál különleges felületet eredményez.',
                'image_name' => 'U68.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 13,
                'tombstone_id' => 'U 57',
                'name' => 'gránit Giallo Veneziano - Nero India',
                'description' => 'A gránit kontrasztja kiemeli a másik anyag színét. A burkolt járdaszegélyen 10 cm-es magasítás, rajta egy 3 cm vastag, nagy fedlap helyezkedik el. A sűllyesztett váza az alsó részre lett helyezve, hogy a virág ne takarja az emléket. Az emlék két lap és két szín kombinációjával készült.',
                'image_name' => 'U57.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 14,
                'tombstone_id' => 'U 17',
                'name' => 'gránit Dalia Red',
                'description' => 'A tömb gránit járdaszegélyre  egy 5 cm vastag, íves elejű fedlapot helyeztünk. A bal alsó ívben kapott helyet a süllyesztett váza. A fedlap "könnyű" íveit követi az emlék, amire arany felirat került.',
                'image_name' => 'U17.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 15,
                'tombstone_id' => 'U 16',
                'name' => 'gránit Nero Impala',
                'description' => 'A burkolt járdaszegélyen 7 cm-es a magasítás, rajta 5 cm vastag szegélykeret és azon egy kis fedlap. Mindegyiknek a jobb eleje kerekítve van. Az emlék, egy lépcsős fényezett falccal készült, bronz karakterekkel.',
                'image_name' => 'U16.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 16,
                'tombstone_id' => 'U 6',
                'name' => 'gránit Nero Assoluto India',
                'description' => 'A ferdére vágott tömb fedlap közvetlenül a burkolt járdaszegélyre került. A fedlap végében hagyott platnira egy esztergált váza került elhelyezésre. Az emlék nélkül készült urna síremlék egyszerűségében magával ragadó.',
                'image_name' => 'U6.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 17,
                'tombstone_id' => 'U 31',
                'name' => 'gránit Rosso Vanga',
                'description' => 'A burkolt járdaszegélyen 10 cm-es magasítás áll, rajta az 5 cm vastag, nagy fedlap, melynek az éle sprengelt. A lépcső és az emlék oldala is sprengelt. Természetes és naturalisztikus hatást kelt.',
                'image_name' => 'U31.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 18,
                'tombstone_id' => 'U 34',
                'name' => 'gránit Kinawa Rose',
                'description' => 'A tömb gránit járdaszegélyen fekszik egy 6 cm vastag, íves elejű fedlap. A bal alsó ívben kapott helyet a süllyesztett, bronz váza. A fedlap "könnyű" íveit követi az emlék, amire aranyozott karakterek kerültek.',
                'image_name' => 'U34.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 19,
                'tombstone_id' => 'U 37',
                'name' => 'gránit Paradiso Classico',
                'description' => 'A nyitott, gránittal burkolt járdaszegélyen egy 5 cm vastag, íves elejű fedlap került, az élő virágnak helyet hagyva. A pozitív és negatív ívekkel tervezett emléket díszíti még a faragott nyers falz. A portré lézergravírozó technológiával készült.',
                'image_name' => 'U37.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 20,
                'tombstone_id' => 'U 39',
                'name' => 'gránit Nero Impala',
                'description' => 'A burkolt gránit járdaszegélyen egy 10 cm vastag, tömb fedlap helyezkedik el. A süllyesztett váza az alsó részre lett helyezve, hogy a virág ne takarja az emléket. A szögletes fedlapra helyezett íves oldalú emlék eltérő stílusú, mégis harmóniát tükröz.',
                'image_name' => 'U39.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 21,
                'tombstone_id' => 'U 41',
                'name' => 'gránit Nero Impala',
                'description' => 'A tömb gránit járdaszegélyen fekszik egy 5 cm vastag, íves elejű fedlap. A bal alsó ívben kapott helyet a süllyesztett váza. Az emlék formája, stilizált vitorlára emlékeztet, amit aranyozott betűk és szomorú fűz díszít.',
                'image_name' => 'U41.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 22,
                'tombstone_id' => 'U 42',
                'name' => 'gránit Nero Impala',
                'description' => 'A gránittal burkolt járdaszegélyen fekszik egy 5 cm vastag, íves elejű fedlap. A bal alsó ívben kapott helyet a váza. A járdán hagyott ívben készült egy furat, ahová élő virágot lehet ültetni. A fedlap "könnyű" íveit követi az emlék, amire arany felirat került.',
                'image_name' => 'U42.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 23,
                'tombstone_id' => 'U 43',
                'name' => 'gránit Vizag Blue',
                'description' => 'A gránittal burkolt járdaszegélyen fekszik egy 6 cm vastag, íves elejű fedlap. A járdán hagyott ívben készült egy furat, ahová élő virágot lehet ültetni. A csúcsos emlék, kiemelkedik környezetéből.',
                'image_name' => 'U43.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 24,
                'tombstone_id' => 'U 10',
                'name' => 'gránit Halmstadt Bararp',
                'description' => 'A burkolt járdaszegélyen fekszik az 5 cm-es szegélykeret. Az amorf emlék, fedlap és a lépcső oldala sprengelt. Természetes és naturalisztikus hatást kelt. A fózolt váza az alsó részre lett helyezve, hogy a virág ne takarja az emléket.',
                'image_name' => 'U10.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 25,
                'tombstone_id' => 'U 46',
                'name' => 'gránit Verde Laguna',
                'description' => 'A burkolt járdaszegélyen áll a 10 cm-es magasítás, rajta a 3 cm vastag, nagy fedlap. A fózolt váza az alsó részre lett helyezve, hogy a virág ne takarja az emléket. Az emlék, két lépcsős, nyers falccal készült, ún. "tulipános" formájú, relief motívumokkal.',
                'image_name' => 'U46.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 26,
                'tombstone_id' => 'U 25',
                'name' => 'gránit Dalia Red',
                'description' => 'A burkolt járdaszegélyen 10 cm-es magasítás, rajta 3 cm vastag, nagy fedlap helyezkedik el. A süllyesztett váza az alsó részre lett helyezve, hogy a virág ne takarja az emléket. Az emlék minden oldala íves, hullámos, hogy megtörje az egyhangúságot.',
                'image_name' => 'U25.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 27,
                'tombstone_id' => 'U 30',
                'name' => 'gránit Vizag Blue',
                'description' => 'A burkolt járdaszegélyen 6 cm vastag, íves elejű fedlap fekszik. A járdán hagyott ívben kapott helyet a süllyesztett váza. Az emlék, egy lépcsős, fényezett falccal készült, relief virág mintával és felirattal, amit kiemel a fehérített háttér',
                'image_name' => 'U30.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 28,
                'tombstone_id' => 'U 23',
                'name' => 'gránit Nero Impala',
                'description' => 'A burkolt járdaszegélyen 10 cm-es magasítás, rajta 5 cm vastag, nagy fedlap található. A süllyesztett váza az alsó részre lett helyezve, hogy a virág ne takarja az emléket, mely két lépcsős, nyers falccal készült, ún. "tulipános" formájú, relief motívumokkal.',
                'image_name' => 'U23.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 29,
                'tombstone_id' => 'U 12',
                'name' => 'gránit Rosso Vanga',
                'description' => 'A tömb gránit járdaszegélyen egy 5 cm vastag, íves elejű fedlap látható. A bal alsó ívben kapott helyet a váza. A fedlap "könnyű" íveit követi az emlék, amire bronz felirat került.',
                'image_name' => 'U12.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 30,
                'tombstone_id' => 'U 15',
                'name' => 'gránit Nero Assoluto India',
                'description' => 'A tömb gránit járdaszegélyen fekszik egy 5 cm vastag, íves elejű fedlap. A bal alsó ívben kapott helyet a váza. A fedlap "könnyű" íveit követi az emlék, amire bronz felirat került.',
                'image_name' => 'U15.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 31,
                'tombstone_id' => 'U 21',
                'name' => 'Juparana ',
                'description' => 'A burkolt járdaszegélyen 7 cm-es magasítás, rajta az 5 cm vastag, nagy, fedlap, melynek az éle sprengelt. Egy elektromos bronz mécses látható a fedlapon, ami elemmel működik. A csúcsos emlék, kiemelkedik környezetéből.',
                'image_name' => 'U21.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 32,
                'tombstone_id' => 'U 62',
                'name' => 'gránit Halmstadt Bararp',
                'description' => 'A  gránittal burkolt járdaszegélyen fekszik egy 10 cm vastag, íves elejű fedlap. A járdán hagyott ívbe helyeztük a vázát. A fedlap "könnyű" íveit követi az emlék, amire bronz felirat került. Az oldalak un. sprengelt  technológiával készültek.',
                'image_name' => 'U62.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 33,
                'tombstone_id' => 'U 38',
                'name' => 'gránit Rosso Vanga',
                'description' => 'A tömb gránit járdaszegélyt egy 5 cm vastag, íves elejű fedlap díszíti. A bal alsó ívben kapott helyet a süllyesztett váza. Az emlék, egy lépcsős, nyers falccal készült, írott arany karakterekkel.',
                'image_name' => 'U38.jpg',
                'group' => 'Urna sírkő 3. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Urna sírkő 4. csoport
            [
                'order' => 1,
                'tombstone_id' => 'U 48',
                'name' => 'gránit Halmstadt - Nero India',
                'description' => 'A két szín kombinációja kiemeli az anyagok kontrasztját. A burkolt járdaszegélyen 12 cm-es a magasítás. A két fedlap hosszú élei gömbölyítettek, egymáshoz képest más magasságban végződnek. A lépcsőbe ezt a szinteltolás bemartuk. Az emlék 2 részét egymásba integráltuk, éleiket gömbölyítettük. A fekete gránitba készített lézergravírozás jól látható a fekete-fehér kontraszt miatt.',
                'image_name' => 'U48.jpg',
                'group' => 'Urna sírkő 4. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'tombstone_id' => 'U 49',
                'name' => 'gránit Halmstadt Bararp',
                'description' => 'A nyitott, gránittal burkolt járdaszegélyen fekszik egy 6 cm vastag, íves elejű fedlap, élő virágnak helyet hagyva. A szív alakú emlék és a kiegészítő lépcső formája, harmóniában van a fedlappal. Az oldalak azonos megmunkálással készültek.',
                'image_name' => 'U49.jpg',
                'group' => 'Urna sírkő 4. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'tombstone_id' => 'U 74',
                'name' => 'gránit Nero Assoluto India',
                'description' => 'A burkolt járdaszegélyen áll a 10 cm-es magasítás, rajta egy 3 cm vastag, nagy fedlap. A lépcsőn lévő emlék formája klasszikus timpanonos, esztergált oszlopokkal és prizmás tetővel.',
                'image_name' => 'U74.jpg',
                'group' => 'Urna sírkő 4. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'tombstone_id' => 'U 22',
                'name' => 'mészkő Aurora - Nero India',
                'description' => 'A két szín kombinációja kiemeli az anyagok kontrasztját. A burkolt járdaszegélyen 12 cm-es a  magasítás. A két fedlap hosszú élei gömbölyítettek, egymáshoz képest más magasságban végződnek. A lépcsőbe ez a szint eltolás be van marva. Az emlék két daradját egymásba  integráltuk, éleiket gömbölyítettük.',
                'image_name' => 'U22.jpg',
                'group' => 'Urna sírkő 4. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'tombstone_id' => 'U 20',
                'name' => 'gránit Verde San Francisco',
                'description' => 'A tömb gránit járdaszegélyen egy nyitott szegélykeret, azon egy 5 cm vastag, íves elejű fedlap helyezkedik el. A nyitva hagyott rész alkalmas élő virág beültetésére. A csúcsos emlék kiemelkedő részébe lett gravírozva egy sportrepülő.',
                'image_name' => 'U20.jpg',
                'group' => 'Urna sírkő 4. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'tombstone_id' => 'U 76',
                'name' => 'gránit Shiwakashi',
                'description' => 'A tömb gránit járdaszegélyen egy nyitott szegélykeret, azon egy 5 cm vastag, íves elejű fedlap látható. A nyitva hagyott rész, alkalmas élő virág beültetésére. A szív alakú emlék és a kiegészítő lépcső formája, harmóniában van a fedlappal. Az oldalak azonos megmunkálással készültek.',
                'image_name' => 'U76.jpg',
                'group' => 'Urna sírkő 4. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'tombstone_id' => 'U 40',
                'name' => 'gránit Paradiso Classico',
                'description' => 'A tömb gránit járdaszegélyen egy nyitott szegélykeret, azon egy 5 cm vastag, íves elejű fedlap kapott helyet. A nyitva hagyott rész alkalmas élő virág beültetésére. A fedlap "könnyű" íveit követi az emlék, amire bronz felirat került.',
                'image_name' => 'U40.jpg',
                'group' => 'Urna sírkő 4. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'tombstone_id' => 'U 47',
                'name' => 'gránit Kinawa Rose',
                'description' => 'A tömb gránit járdaszegélyen egy nyitott szegélykeret, azon egy 5 cm vastag, íves elejű fedlap látható. A nyitva hagyott rész, alkalmas élő virág beültetésére. Az emlék két lépcsős, nyers falccal készült, ún. "tulipános" formájú, arany karakterekkel.',
                'image_name' => 'U47.jpg',
                'group' => 'Urna sírkő 4. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'tombstone_id' => 'U 73',
                'name' => 'márvány Ruskicai',
                'description' => 'A nyitott, gránittal burkolt járdaszegélyen fekszik egy 10 cm vastag, íves elejű fedlap. A szív alakú emlék és a kiegészítő lépcső formája, harmóniában van a fedlappal. A kiegészítő lapon látható márványból készült sűllyesztett váza. Az oldalak azonos megmunkálással készültek.',
                'image_name' => 'U73.jpg',
                'group' => 'Urna sírkő 4. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'tombstone_id' => 'U 11',
                'name' => 'gránit Nero Assoluto India',
                'description' => 'A burkolt járdaszegélyen 5 cm-es magasítás, rajta a 6 cm vastag, nagy fedlap kapott helyet. A süllyesztett vázát az alsó részre helyeztük, hogy a virág ne takarja az emléket, melynek formáját kiemeli a nyers, faragott legyező.',
                'image_name' => 'U11.jpg',
                'group' => 'Urna sírkő 4. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 11,
                'tombstone_id' => 'U 26',
                'name' => 'gránit Olive Green',
                'description' => 'A nyitott, gránittal burkolt járdaszegélyre egy 10 cm vastag, íves elejű fedlap került, élő virágnak helyet hagyva. Az emlék hasonlít a "zászlós" formára, de egy kicsit mozgalmasabbá tettük egy negatív ívvel.',
                'image_name' => 'U26.jpg',
                'group' => 'Urna sírkő 4. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 12,
                'tombstone_id' => 'U 36',
                'name' => 'gránit Labrador Black',
                'description' => 'A burkolt járdaszegélyen áll a 10 cm-es magasítás, rajta egy 5 cm vastag, nagy fedlap. Az emlék két lépcsős, nyers falccal készült, ún. "tulipános" formájú, relief karakterekkel.',
                'image_name' => 'U36.jpg',
                'group' => 'Urna sírkő 4. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 13,
                'tombstone_id' => 'U 14',
                'name' => 'gránit Dalia Red',
                'description' => 'Az alsó járda nyújtott, hogy több élő virágot lehessen beleültetni. A felső járdaszegélyen fekszik egy 5 cm vastag, íves elejű fedlap. A járdán hagyott ívben kapott helyet egy esztergált váza. A fedlap "könnyű" íveit követi az emlék, amire bronz felirat került.',
                'image_name' => 'U14.jpg',
                'group' => 'Urna sírkő 4. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 14,
                'tombstone_id' => 'U 19',
                'name' => 'gránit Brazulite Sucuru',
                'description' => 'A tömb gránit járdaszegélyen fekszik egy nyitott szegélykeret, azon egy 5 cm vastag, íves elejű fedlap. A nyitva hagyott rész alkalmas élő virág beültetésére. A fedlap "könnyű" íveit követi az emlék, amire bronz felirat került.',
                'image_name' => 'U19.jpg',
                'group' => 'Urna sírkő 4. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 15,
                'tombstone_id' => 'U 18',
                'name' => 'gránit Halmstadt Bararp',
                'description' => 'A tömb gránit járdaszegélyre egy 5 cm vastag, íves elejű fedlapot helyeztünk el. A bal alsó ívben kapott helyet a bronz, süllyesztett váza. A fedlap "könnyű" íveit követi az emlék, amire bronz felirat került.',
                'image_name' => 'U18.jpg',
                'group' => 'Urna sírkő 4. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 16,
                'tombstone_id' => 'U 29',
                'name' => 'gránit Royal Mahogany',
                'description' => 'A tömb gránit járdaszegélyen 10 cm vastag, íves elejű fedlap fekszik . A bal alsó ívben kapott helyet a süllyesztett váza. Az emlék formája, régi tradíciókat elevenít fel.',
                'image_name' => 'U29.jpg',
                'group' => 'Urna sírkő 4. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 17,
                'tombstone_id' => 'U 13',
                'name' => 'gránit Verde San Francisco',
                'description' => 'A tömb gránit járdaszegélyen egy 7 cm vastag fedlap kapott helyet, amire ráhelyeztük az emléket. A két kő formailag szinte azonos, a profilja félkörívesen gömbölyített. A cél az volt, hogy kavicsra emlékeztessen.',
                'image_name' => 'U13.jpg',
                'group' => 'Urna sírkő 4. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 18,
                'tombstone_id' => 'U 44',
                'name' => 'gránit Olive Green',
                'description' => 'A gránittal burkolt járdaszegélyen fekszik egy 5 cm vastag, íves elejű fedlap. A bal alsó ívben kapott helyet a váza. A járdán hagyott ívben készült egy furat, ahová élő virágot lehet ültetni. Az emlék, egy lépcsős nyers falccal készült, írott arany karakterekkel és kereszttel.',
                'image_name' => 'U44.jpg',
                'group' => 'Urna sírkő 4. csoport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
