/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    'sirko': RouteRecordInfo<'sirko', '/sirko', Record<never, never>, Record<never, never>>,
    'urna-sirko': RouteRecordInfo<'urna-sirko', '/sirko/urna-sirko', Record<never, never>, Record<never, never>>,
    'urna-sirko-csoport-1': RouteRecordInfo<'urna-sirko-csoport-1', '/sirko/urna-sirko/urna-csoport-1', Record<never, never>, Record<never, never>>,
    'urna-sirko-csoport-2': RouteRecordInfo<'urna-sirko-csoport-2', '/sirko/urna-sirko/urna-csoport-2', Record<never, never>, Record<never, never>>,
    'urna-sirko-csoport-3': RouteRecordInfo<'urna-sirko-csoport-3', '/sirko/urna-sirko/urna-csoport-3', Record<never, never>, Record<never, never>>,
    'urna-sirko-csoport-4': RouteRecordInfo<'urna-sirko-csoport-4', '/sirko/urna-sirko/urna-csoport-4', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: 'home'
      views: never
    }
    'src/pages/sirko/index.vue': {
      routes: 'sirko'
      views: never
    }
    'src/pages/sirko/urna-sirko/index.vue': {
      routes: 'urna-sirko'
      views: never
    }
    'src/pages/sirko/urna-sirko/urna-csoport-1.vue': {
      routes: 'urna-sirko-csoport-1'
      views: never
    }
    'src/pages/sirko/urna-sirko/urna-csoport-2.vue': {
      routes: 'urna-sirko-csoport-2'
      views: never
    }
    'src/pages/sirko/urna-sirko/urna-csoport-3.vue': {
      routes: 'urna-sirko-csoport-3'
      views: never
    }
    'src/pages/sirko/urna-sirko/urna-csoport-4.vue': {
      routes: 'urna-sirko-csoport-4'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
