/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    'epiteszet': RouteRecordInfo<'epiteszet', '/epiteszet', Record<never, never>, Record<never, never>>,
    'sirko': RouteRecordInfo<'sirko', '/sirko', Record<never, never>, Record<never, never>>,
    'akcios-sirko': RouteRecordInfo<'akcios-sirko', '/sirko/akcios-sirko', Record<never, never>, Record<never, never>>,
    'dupla-sirko': RouteRecordInfo<'dupla-sirko', '/sirko/dupla-sirko', Record<never, never>, Record<never, never>>,
    'dupla-sirko-csoport-1': RouteRecordInfo<'dupla-sirko-csoport-1', '/sirko/dupla-sirko/dupla-csoport-1', Record<never, never>, Record<never, never>>,
    'dupla-sirko-csoport-2': RouteRecordInfo<'dupla-sirko-csoport-2', '/sirko/dupla-sirko/dupla-csoport-2', Record<never, never>, Record<never, never>>,
    'dupla-sirko-csoport-3': RouteRecordInfo<'dupla-sirko-csoport-3', '/sirko/dupla-sirko/dupla-csoport-3', Record<never, never>, Record<never, never>>,
    'dupla-sirko-csoport-4': RouteRecordInfo<'dupla-sirko-csoport-4', '/sirko/dupla-sirko/dupla-csoport-4', Record<never, never>, Record<never, never>>,
    'kripta-sirko': RouteRecordInfo<'kripta-sirko', '/sirko/kripta-sirko', Record<never, never>, Record<never, never>>,
    'kulonleges-sirko': RouteRecordInfo<'kulonleges-sirko', '/sirko/kulonleges-sirko', Record<never, never>, Record<never, never>>,
    'marvany-sirko': RouteRecordInfo<'marvany-sirko', '/sirko/marvany-sirko', Record<never, never>, Record<never, never>>,
    'meszko-sirko': RouteRecordInfo<'meszko-sirko', '/sirko/meszko-sirko', Record<never, never>, Record<never, never>>,
    'sirko-kellekek': RouteRecordInfo<'sirko-kellekek', '/sirko/sirko-kellekek', Record<never, never>, Record<never, never>>,
    'sirko-kellekek-bronz-sirko-kellekek': RouteRecordInfo<'sirko-kellekek-bronz-sirko-kellekek', '/sirko/sirko-kellekek/bronz-sirko-kellekek', Record<never, never>, Record<never, never>>,
    'sirko-kellekek-ko-mecsestarto': RouteRecordInfo<'sirko-kellekek-ko-mecsestarto', '/sirko/sirko-kellekek/ko-mecsestarto', Record<never, never>, Record<never, never>>,
    'sirko-kellekek-ko-vaza': RouteRecordInfo<'sirko-kellekek-ko-vaza', '/sirko/sirko-kellekek/ko-vaza', Record<never, never>, Record<never, never>>,
    'sirko-kellekek-ko-viragtarto': RouteRecordInfo<'sirko-kellekek-ko-viragtarto', '/sirko/sirko-kellekek/ko-viragtarto', Record<never, never>, Record<never, never>>,
    'sirko-kellekek-sirfelirat': RouteRecordInfo<'sirko-kellekek-sirfelirat', '/sirko/sirko-kellekek/sirfelirat', Record<never, never>, Record<never, never>>,
    'sirko-keszites': RouteRecordInfo<'sirko-keszites', '/sirko/sirko-keszites', Record<never, never>, Record<never, never>>,
    'szimpla-sirko': RouteRecordInfo<'szimpla-sirko', '/sirko/szimpla-sirko', Record<never, never>, Record<never, never>>,
    'szimpla-sirko-csoport-1': RouteRecordInfo<'szimpla-sirko-csoport-1', '/sirko/szimpla-sirko/szimpla-csoport-1', Record<never, never>, Record<never, never>>,
    'szimpla-sirko-csoport-2': RouteRecordInfo<'szimpla-sirko-csoport-2', '/sirko/szimpla-sirko/szimpla-csoport-2', Record<never, never>, Record<never, never>>,
    'szimpla-sirko-csoport-3': RouteRecordInfo<'szimpla-sirko-csoport-3', '/sirko/szimpla-sirko/szimpla-csoport-3', Record<never, never>, Record<never, never>>,
    'szimpla-sirko-csoport-4': RouteRecordInfo<'szimpla-sirko-csoport-4', '/sirko/szimpla-sirko/szimpla-csoport-4', Record<never, never>, Record<never, never>>,
    'urna-sirko': RouteRecordInfo<'urna-sirko', '/sirko/urna-sirko', Record<never, never>, Record<never, never>>,
    'urna-sirko-csoport-1': RouteRecordInfo<'urna-sirko-csoport-1', '/sirko/urna-sirko/urna-csoport-1', Record<never, never>, Record<never, never>>,
    'urna-sirko-csoport-2': RouteRecordInfo<'urna-sirko-csoport-2', '/sirko/urna-sirko/urna-csoport-2', Record<never, never>, Record<never, never>>,
    'urna-sirko-csoport-3': RouteRecordInfo<'urna-sirko-csoport-3', '/sirko/urna-sirko/urna-csoport-3', Record<never, never>, Record<never, never>>,
    'urna-sirko-csoport-4': RouteRecordInfo<'urna-sirko-csoport-4', '/sirko/urna-sirko/urna-csoport-4', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: 'home'
      views: never
    }
    'src/pages/epiteszet/index.vue': {
      routes: 'epiteszet'
      views: never
    }
    'src/pages/sirko/index.vue': {
      routes: 'sirko'
      views: never
    }
    'src/pages/sirko/akcios-sirko/index.vue': {
      routes: 'akcios-sirko'
      views: never
    }
    'src/pages/sirko/dupla-sirko/index.vue': {
      routes: 'dupla-sirko'
      views: never
    }
    'src/pages/sirko/dupla-sirko/dupla-csoport-1.vue': {
      routes: 'dupla-sirko-csoport-1'
      views: never
    }
    'src/pages/sirko/dupla-sirko/dupla-csoport-2.vue': {
      routes: 'dupla-sirko-csoport-2'
      views: never
    }
    'src/pages/sirko/dupla-sirko/dupla-csoport-3.vue': {
      routes: 'dupla-sirko-csoport-3'
      views: never
    }
    'src/pages/sirko/dupla-sirko/dupla-csoport-4.vue': {
      routes: 'dupla-sirko-csoport-4'
      views: never
    }
    'src/pages/sirko/kripta-sirko/index.vue': {
      routes: 'kripta-sirko'
      views: never
    }
    'src/pages/sirko/kulonleges-sirko/index.vue': {
      routes: 'kulonleges-sirko'
      views: never
    }
    'src/pages/sirko/marvany-sirko/index.vue': {
      routes: 'marvany-sirko'
      views: never
    }
    'src/pages/sirko/meszko-sirko/index.vue': {
      routes: 'meszko-sirko'
      views: never
    }
    'src/pages/sirko/sirko-kellekek/index.vue': {
      routes: 'sirko-kellekek'
      views: never
    }
    'src/pages/sirko/sirko-kellekek/bronz-sirko-kellekek.vue': {
      routes: 'sirko-kellekek-bronz-sirko-kellekek'
      views: never
    }
    'src/pages/sirko/sirko-kellekek/ko-mecsestarto.vue': {
      routes: 'sirko-kellekek-ko-mecsestarto'
      views: never
    }
    'src/pages/sirko/sirko-kellekek/ko-vaza.vue': {
      routes: 'sirko-kellekek-ko-vaza'
      views: never
    }
    'src/pages/sirko/sirko-kellekek/ko-viragtarto.vue': {
      routes: 'sirko-kellekek-ko-viragtarto'
      views: never
    }
    'src/pages/sirko/sirko-kellekek/sirfelirat.vue': {
      routes: 'sirko-kellekek-sirfelirat'
      views: never
    }
    'src/pages/sirko/sirko-keszites/index.vue': {
      routes: 'sirko-keszites'
      views: never
    }
    'src/pages/sirko/szimpla-sirko/index.vue': {
      routes: 'szimpla-sirko'
      views: never
    }
    'src/pages/sirko/szimpla-sirko/szimpla-csoport-1.vue': {
      routes: 'szimpla-sirko-csoport-1'
      views: never
    }
    'src/pages/sirko/szimpla-sirko/szimpla-csoport-2.vue': {
      routes: 'szimpla-sirko-csoport-2'
      views: never
    }
    'src/pages/sirko/szimpla-sirko/szimpla-csoport-3.vue': {
      routes: 'szimpla-sirko-csoport-3'
      views: never
    }
    'src/pages/sirko/szimpla-sirko/szimpla-csoport-4.vue': {
      routes: 'szimpla-sirko-csoport-4'
      views: never
    }
    'src/pages/sirko/urna-sirko/index.vue': {
      routes: 'urna-sirko'
      views: never
    }
    'src/pages/sirko/urna-sirko/urna-csoport-1.vue': {
      routes: 'urna-sirko-csoport-1'
      views: never
    }
    'src/pages/sirko/urna-sirko/urna-csoport-2.vue': {
      routes: 'urna-sirko-csoport-2'
      views: never
    }
    'src/pages/sirko/urna-sirko/urna-csoport-3.vue': {
      routes: 'urna-sirko-csoport-3'
      views: never
    }
    'src/pages/sirko/urna-sirko/urna-csoport-4.vue': {
      routes: 'urna-sirko-csoport-4'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
